### ISSUE TITLE
ownCloud Not Being Fixed

### ISSUE THREAD

**Issue by Foggalong** [bilelmoussaoui/Hardcode-Tray#226]
From what I understand the PPA introduced in #198 was designed to fix the problem of the patched SNI-Qt PPA not being available for 16.04 and above. I'm still having the same issue even with the new one though.

My system is Ubuntu 16.10 with XFCE Panel, and ownCloud 2.2.2 says it's being fixed by the script but remains hardcoded.

**Comment by bil-elmoussaoui** [comment]
Do you have any other qt application installed ? In order to verify if it's a sin-qt issue or something else

**Comment by Foggalong** [comment]
I don't, but I'd be willing to install one to test. Recommendation?

**Comment by bil-elmoussaoui** [comment]
You can try megasync

**Comment by Foggalong** [comment]
@bil-elmoussaoui Preferably something in the Ubuntu repos, though I'll try Mega if nothing else.

**Comment by bil-elmoussaoui** [comment]
You can still try the old skype version, if i still remember it's on Ubuntu ppa

**Comment by varlesh** [comment]
i confirm this, new version not see megasync:
![image](https://cloud.githubusercontent.com/assets/8083855/20634520/26cd035a-b363-11e6-900a-808f4b068cd9.png)

**Comment by bil-elmoussaoui** [comment]
@varlesh Have you ran the script after installing megasync?

**Comment by varlesh** [comment]
of course

**Comment by varlesh** [comment]
Maybe change paths? Because icon reverted:
```
alex@dell:~$ hardcode-tray
[sudo] пароль для alex: 
Welcome to the tray icons hardcoder fixer!
Your indicator icon size is : 22
Your current icon theme is : Papirus-Dark-GTK
Svg to png functions are : Enabled
Applications will be fixed : All
1 - Apply
2 - Revert
Please choose: 2
Reverting now..

Clementine -- reverted
Clementine -- reverted
Google Chrome -- reverted
Guake -- reverted
Megasync -- reverted
Telegram -- reverted

Done, Thank you for using the Hardcode-Tray fixer!
alex@dell:~$ 
```

**Comment by varlesh** [comment]
on tmp
![image](https://cloud.githubusercontent.com/assets/8083855/20634586/9c522948-b363-11e6-877f-0a55101060dd.png)

**Comment by bil-elmoussaoui** [comment]
Those icons are already in the database, it seems that either MegaSync ships it's own version of libsni-qt or that the patch we used to use is not working anymore :(

**Comment by varlesh** [comment]
Ok, i'm now test with old version (Not json)...

**Comment by varlesh** [comment]
With old version 9aad49a67c004b314dbdb4cddbc512e8d552e6f7 worked, JSON-version very bugged.
![image](https://cloud.githubusercontent.com/assets/8083855/20634736/13c11c86-b365-11e6-8ea6-243349cc5516.png)

**Comment by bil-elmoussaoui** [comment]
Fixed the issue for json version, can you try again?

**Comment by varlesh** [comment]
Also for better looking need add status for changed icons, how reverted:
```
Clementine -- reverted
Google Chrome -- reverted
Guake -- reverted
Megasync -- reverted
```
Yes show progress, but i'm not see what apps changed. For example:
```
Clementine -- fixed
Google Chrome --  fixed
Guake --  fixed
Megasync --  fixed
```

**Comment by varlesh** [comment]
Mega worked with fresh git-version!

**Comment by bil-elmoussaoui** [comment]
Also @Foggalong i might need to see the content of /tmp the icon names might have changed..

**Comment by bil-elmoussaoui** [comment]
@Foggalong Can you show me the output of `owncloud --version`

**Comment by Foggalong** [comment]
@bil-elmoussaoui Will double check when I'm back with my computer, but it's just the latest version in the Ubuntu repos so I assume [2.2.2](http://packages.ubuntu.com/yakkety/owncloud-client)

**Comment by bil-elmoussaoui** [comment]
I just installed xubuntu here, installed owncloud from the main repository.
xubuntu info 
```bash
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
```
OwnCloud version 
```bash
ownCloud version 2.1.1
Using Qt 5.5.1
```
Once i've installed everything, i ran OwnCloud, and the icons was ugly. I ran Hardcode-tray and i had the same result. I checked `/tmp` and i found those icons
![screenshot_2016-12-01_00-49-19](https://cloud.githubusercontent.com/assets/7660997/20776311/0c02e55c-b760-11e6-8854-ea7e883f0626.png)
I will report back if i have any news

**Comment by Daniil08** [comment]
I turned on indicators in the main settings of cinnamon and megasync started to work
![2016-12-03 09-58-29](https://cloud.githubusercontent.com/assets/24314159/20857483/1b0e731e-b93f-11e6-95cc-4f990327bce3.png)

**Comment by bil-elmoussaoui** [comment]
@Foggalong Can you try this new PPA by @wa4557 https://code.launchpad.net/~andreas-angerer89/+archive/ubuntu/sni-qt-patched . We are going to patch sni-qt directly, and add few features in the future if possible.

**Comment by Foggalong** [comment]
Will test that sure :+1:

**Comment by varlesh** [comment]
@Daniil08 i think better use another color for cinnamon tray on Arc Dark, because colors different with papirus:
```
sudo sed -i 's|#ffffff|#d3dae3|g' /usr/share/themes/Arc-Dark/cinnamon/cinnamon.css
```

**Comment by Foggalong** [comment]
Nope, still isn't working. After running the script it also seems to have unlinked my ownCloud account from the syncing app which is really weird. It really shouldn't be doing anything that can cause that :/

**Comment by wa4557** [comment]
@bil-elmoussaoui Owncloud is not using sni-qt, but native `QIcon`. I'm not sure why it isn't fixed though, shoud be possible to theme them

**Comment by bil-elmoussaoui** [comment]
It's using sni-qt as far as i know, see #56

**Comment by bil-elmoussaoui** [comment]
@wa4557 In my system, gnome 3.22 with Arch linux, OwnCloud use the icon from the theme directly. So my guess, is that owncloud supports all the possible ways to create a tray icon on Linux; We just need a library as dependency in order to force OwnCloud to use sni-qt instead of QIcon

**Comment by bil-elmoussaoui** [comment]
@Foggalong Qt5 dropped the support of sni-qt, and we won't be able to support those applications (at the moment). So, it's a different issue that should be opened instead of this one for Qt5 support. It seems that they use http://packages.ubuntu.com/trusty/libdbusmenu-qt5-dev to draw the tray. But no idea if they do use the same library to draw tray icons too!
I will close this and open a proper issue for Qt5

**Comment by wa4557** [comment]
I want to reopen this. Owncloud should be working (so it tries to look for a system theme icon) but isn't on most systems because it ships its own Qt version which does not find the current icon theme. I opened a bug report https://github.com/owncloud/client/issues/6036 but I'm not sure this is easily fixable

**Comment by bil-elmoussaoui** [comment]
Alright, even if it's an upstream issue but keeping this open will help us keep track of the upstream issue 👍

**Comment by bilelmoussaoui** [comment]
Upstream took care of the issue. Not released yet but it's already on master.
