### ISSUE TITLE
Can we replace icons in binary apps?

### ISSUE THREAD

**Issue by bilelmoussaoui** [bilelmoussaoui/Hardcode-Tray#297]
I was doing some tests in order to fix some sni-qt issues and i created a python code that replaces specific png files in a binary file. Which includes skype, or any other application that has it icons hardcoded in the binary file. 
And i'm wondering if we have the right to do that? Will that cause us any problem? 
i've tried my code with skype, Jetbrains Toolbox, OBS, and OwnCloud using Qt5. This does not work at all for nwjs as it's just a zip file with some bytes at it beginning.

**Comment by wa4557** [comment]
I don't see a reason why not, if it works. I would say we should try everything else first, but if that is the only way to change I would say it is ok. Licencing stuff might be a problem though for not FOSS software

**Comment by KottV** [comment]
as some idea, there is old project, that replaces skype tray icons via ldpreload:
https://github.com/derlaft/skype1ico

imho it's preferable than modify binary

**Comment by bil-elmoussaoui** [comment]
@KottV Yeah it seem to be a good solution :) it was more of a question; Just in case we are out of solutions; especially for Qt5 applications..

**Comment by Foggalong** [comment]
The idea of modifying binaries definitely questionable from a licensing point of view, so you'd probably never be able to get it included in official repositories. However reverse engineering and workarounds like this aren't uncommon in the Linux community so I wouldn't worry about it too much.

**Comment by bil-elmoussaoui** [comment]
Yeah :) i was more afraid of licensing! I will push an alpha version of my code in a different branch and we will see if it works as expected

**Comment by wa4557** [comment]
This app will never go into official repos anyways because it replaces to much stuff in `/usr` and other nonuser directories. So I would say that if licencing allows it (MIT and GPL3/2 should be ok?), it's ko

**Comment by bilelmoussaoui** [comment]
Closing this as it's not an easy way to deal with the issue.
