### ISSUE TITLE
Discord 0.0.4 support

### ISSUE THREAD

**Issue by Xonha** [bilelmoussaoui/Hardcode-Tray#497]
### Specifications
- Hardcode-Tray version : `4.2`
- Distribution : `Ubuntu 16.04`
- Gtk version : `3.18`
- Inkscape version : `0.91`
- Application name :  `Discord`
- Application version : `0.0.4`

Terminal shows it been replaced but it does not work

![screenshot from 2018-02-09 11-46-21](https://user-images.githubusercontent.com/25267506/36030706-6755fa4e-0d8f-11e8-8e2c-7cb1bd5fc5ba.png)

**Comment by HenriqueY** [comment]
Should i use the other post? Its marked as closed

**Comment by HenriqueY** [comment]
Should i use the other post? It's marked as closed

**Comment by bil-elmoussaoui** [comment]
Nop it's alright, the others commented on a closed post about an old version of Discord...
Will take a look as soon as I can!

**Comment by bil-elmoussaoui** [comment]
Okay, I have done some tests. It's not possible the icons in `$HOME/.config/discord/` as the icons get replaced the moment you start Discord. 
It will require some backend implementation of this kind of applications

**Comment by redg3ar** [comment]
looks to be inside <discord install root>/resources/bootstrap/discord_desktop_core.zip/core.asar/app/images/systemtray

**Comment by redg3ar** [comment]
just a friendly reminder that this replacement method works, ive tried it @bilelmoussaoui

**Comment by bilelmoussaoui** [comment]
I know that It does work. I just need to find some free time to implement this. Will try to take a look as soon as I can

**Comment by MrTimscampi** [comment]
FYI in the meantime I made a quick bash script to do it automatically (Currently supports only Fedora and Papirus, feel free to make PRs for multiple theme support and to add other distros).

You can find it here: https://github.com/MrTimscampi/scripts/blob/master/update-discord-tray

**Comment by yarisgutierrez** [comment]
Has there been any updates on fixing support for version 0.0.5 of Discord?

**Comment by bilelmoussaoui** [comment]
There will be a new release in the near future! Just need to find some free time to work on the next release.

**Comment by rauldipeas** [comment]
I made a [**script**](http://my.opendesktop.org/s/zXGcGonKbD4ERYb) to **Xubuntu 20.04**, with **Discord 0.0.10**.
![ksnip_20200510-011029](https://user-images.githubusercontent.com/12108031/81490628-0c0bca80-925b-11ea-818d-1fab764d8e45.png)

**Comment by mateushonorato** [comment]
> I made a [**script**](http://my.opendesktop.org/s/zXGcGonKbD4ERYb) to **Xubuntu 20.04**, with **Discord 0.0.10**.
> ![ksnip_20200510-011029](https://user-images.githubusercontent.com/12108031/81490628-0c0bca80-925b-11ea-818d-1fab764d8e45.png)

your desktop looks SO COOL
can you send me the extensions and themes you used?

**Comment by rauldipeas** [comment]
> > I made a [**script**](http://my.opendesktop.org/s/zXGcGonKbD4ERYb) to **Xubuntu 20.04**, with **Discord 0.0.10**.
> > ![ksnip_20200510-011029](https://user-images.githubusercontent.com/12108031/81490628-0c0bca80-925b-11ea-818d-1fab764d8e45.png)
> 
> your desktop looks SO COOL
> can you send me the extensions and themes you used?

https://rauldipeas.github.io/xfscripts

**Comment by varlesh** [comment]
@drunkdos georgeat8 @AlexyBot 0.0.13 now supported. See last commit

**Comment by varlesh** [comment]
Sorry guys, i think it's can be fixed on 0.0.4 and higher...
PS: I'm not use Discord and don't know that icons located to **core.asar** in home directory
Thx @rauldipeas Your script help me understand where located icons, because i'm not found info abot tray on sources.
PS2: @rauldipeas not need replace unpacked PNG-icons on `~/.config/discord` This icons automaticaly extracted from **core.asar** with run application
PS3 @drunkdos If icon not show on tray, try `killall -9 Discord` I think it's happened with check updates and application freezed.
