### ISSUE TITLE
No icon for YakYak (it is in list)

### ISSUE THREAD

**Issue by qAnAthemA** [bilelmoussaoui/Hardcode-Tray#511]
### Specifications
- Hardcode-Tray version : `4.2`
- Distribution : `Linux Mint 18.3 Cinnamon`
- Gtk version : `3.18`
- Application name :  `YakYak`
- Application version : `1.5.0`

### Expected behavior and actual behavior

Expected the icon to be changed. However, hardcode-tray did not recognize that YakYak was installed.

### Steps to reproduce the problem
1. Install YakYak
2. Enable tray icon for YakYak in the settings
3. Run "sudo hardcode-tray", then choose option 1 to apply icons.

**Comment by bilelmoussaoui** [comment]
Going to update the database file tonight. Sorry for the long delay
