### ISSUE TITLE
Some icons remain the same after appling hardcode-tray

### ISSUE THREAD

**Issue by yn4v4s** [bilelmoussaoui/Hardcode-Tray#512]
### Specifications
- Hardcode-Tray version : 4.2
- Distribution : KDE neon User Edition 5.12.4
- Gtk version : 3.18
- Sni-qt version: 0.2.7+20161212~1

The applications are Google Chrome (Version 65.0.3325.181) and Caprine 2.11.0

This is the output:
```
potter@ripjaws:~$ sudo -E hardcode-tray --conversion-tool RSVGConvert --size 22 --theme Papirus
Welcome to Hardcode-Tray!
Desktop Environment: Kde
Scaling Factor: 1
Icon Size: 22
Icon Theme: Papirus
Conversion Tool: RSVGConvert
To Do: All
1 - Apply
2 - Revert
3 - Clear Backup Cache
Please choose: 1
Applying now..


Caprine             [#########...........................] 1/4 25.0% 0.11s
Google Chrome       [##################..................] 2/4 50.0% 0.14s
Megasync            [###########################.........] 3/4 75.0% 0.03s
Telegram            [####################################] 4/4 100.0% 0.28s
Took 0.56s to finish the tasks

Done, Thank you for using the Hardcode-Tray fixer!
```
[02-04-2018_10-47-43.log](https://github.com/bilelmoussaoui/Hardcode-Tray/files/1868359/02-04-2018_10-47-43.log)

**Comment by bilelmoussaoui** [comment]
Will fix that tonight. Sorry for the delay

**Comment by jhillix** [comment]
I'm also experiencing this exact same error - assuming it hasn't been resolved yet?

**Comment by bilelmoussaoui** [comment]
@jhillix it's might be an issue with the extension you're using. Both apps uses PNG icons. You can force the icon size of those apps using `sudo -E hardcode-tray --only slack,mailspring  --size 24 --apply`

**Comment by jhillix** [comment]
I just ran `sudo -E hardcode-tray --only slack,mailspring --size 24 --apply` and the result is the same. When you say the extension I'm using, arRSVGConvertRSVGConvert do you mean Inkscape/RSVGConvert, etc.?

**Comment by bilelmoussaoui** [comment]
@jhillix Which distro/DE are you using?

**Comment by bilelmoussaoui** [comment]
Fixed caprine on master. Going to fix Chrome & Chromium latest tonight and release a new version as soon as possible

**Comment by yn4v4s** [comment]
When will you release a new version; please, I can't compile due to dependencies issues.

**Comment by Grief** [comment]
@bilelmoussaoui any progress on that?

**Comment by bilelmoussaoui** [comment]
All of the issues related to this are fixed on master. I'm not going to create a new release any time soon. You can use the master branch which is stable. But I would like to work on some other stuff before the new release.
Please next time, create an issue per application this will allow other users to find an issue easily. 

Closing.
