### ISSUE TITLE
Does not show any icon. Ubuntu 18.04 beta 2

### ISSUE THREAD

**Issue by jibran666** [bilelmoussaoui/Hardcode-Tray#515]
### Specifications
- Hardcode-Tray version : `4.3`
- Distribution : `Ubuntu MATE 18.04 BETA 2`
- Gtk version : `3.22`
- Inkscape version : `` if installed
- Cairo version : `` if installed
- Sni-qt version: `` if installed
- Application name :  ``
- Application version : ``

### Expected behavior and actual behavior
does not show any icons images on the tray that are fixed.

### Steps to reproduce the problem
1. just compile from source
2. apply it.
3.

**Comment by bilelmoussaoui** [comment]
Can you paste the output of `sudo -E hardcode-tray --apply` and the logs that you can find in /tmp/Hardcode-Tray/?

**Comment by bilelmoussaoui** [comment]
Any news?

**Comment by Feichtmeier** [comment]
The ppa is not updated for 18.04 at the moment but I guess you are aware of that anyways just in case you aren't =) Best regards

**Comment by jibran666** [comment]
** (hardcode-tray:10685): WARNING **: 00:39:43.510: Unable to connect to dbus: The connection is closed
Welcome to Hardcode-Tray!
Hardcode-Tray replaces some icons on the binary files of some applications. 
Please close all the running applications before running Hardcode-Tray script.
Desktop Environment: Mate
Scaling Factor: 1
Icon Size: 22
Icon Theme: Papirus-Dark
Conversion Tool: ImageMagick
To Do: All
Applying now..


Chromium            [####................................] 1/8 12.5% 0.66s
Franz               [#########...........................] 2/8 25.0% 6.14s
Google Chrome       [##############......................] 3/8 37.5% 1.81s
Liferea             [##################..................] 4/8 50.0% 0.21s
Messenger           [######################..............] 5/8 62.5% 3.68s
Skype               [###########################.........] 6/8 75.0% 12.79s
Teamviewer          [################################....] 7/8 87.5% 0.00s
WebTorrent Desktop  [####################################] 8/8 100.0% 0.77s
Took 26.07s to finish the tasks

Done, Thank you for using the Hardcode-Tray fixer!

log
[DEBUG] 2018-04-19 00:39:43 DE: Mate
[DEBUG] 2018-04-19 00:39:43 Config file: Not found.
[DEBUG] 2018-04-19 00:39:43 Arguments/Icon Size: None
[DEBUG] 2018-04-19 00:39:43 System/Icon Size: 22
[DEBUG] 2018-04-19 00:39:43 System/Theme: Papirus-Dark
[DEBUG] 2018-04-19 00:39:43 Arguments/Conversion Tool: None
[DEBUG] 2018-04-19 00:39:43 Config/Conversion Tool: None
[DEBUG] 2018-04-19 00:39:43 SVG Factory: Failed Inkscape
[DEBUG] 2018-04-19 00:39:43 SVG Factory: Failed CairoSVG
[DEBUG] 2018-04-19 00:39:43 SVG Factory: Failed RSVGConvert
[DEBUG] 2018-04-19 00:39:43 SVG Factory: Failed SVGExport
[DEBUG] 2018-04-19 00:39:43 SVG Factory: Import ImageMagick
[DEBUG] 2018-04-19 00:39:43 Path with condition: dropbox_callback /home/jibran666/.dropbox-dist/{dropbox}/images/hicolor/16x16/status/
[DEBUG] 2018-04-19 00:39:43 Path with condition: hangouts_callback /home/jibran666/.config/chromium/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/{hangouts}/images_5/
[DEBUG] 2018-04-19 00:39:43 Path with condition: hangouts_callback /home/jibran666/.config/google-chrome/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/{hangouts}/images_5/
[DEBUG] 2018-04-19 00:39:43 Path with condition: hangouts_callback /home/jibran666/.config/google-chrome-beta/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/{hangouts}/images_5/
[DEBUG] 2018-04-19 00:39:43 Path with condition: hangouts_callback /home/jibran666/.config/google-chrome-unstable/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/{hangouts}/images_5/
[DEBUG] 2018-04-19 00:39:43 Path with condition: hangouts_callback /home/jibran666/.config/vivaldi/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/{hangouts}/images_5/
[DEBUG] 2018-04-19 00:39:43 Path with condition: hangouts_callback /home/jibran666/.config/vivaldi-beta/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/{hangouts}/images_5/
[DEBUG] 2018-04-19 00:39:43 Path with condition: hangouts_callback /home/jibran666/.config/vivaldi-snapshot/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/{hangouts}/images_5/
[DEBUG] 2018-04-19 00:39:43 Creating directory: /home/jibran666/.local/share/sni-qt/icons/TVGuiDelegate/22/
[DEBUG] 2018-04-19 00:39:43 Config/Backup Ignore: False
[DEBUG] 2018-04-19 00:39:43 Create new backup folder for Chromium
[DEBUG] 2018-04-19 00:39:43 Creating directory: /home/jibran666/.config/Hardcode-Tray/Chromium/2018-04-19 00:39:43/
[DEBUG] 2018-04-19 00:39:43 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/google-chrome-tray.svg /tmp/tmpgypbqaln
[ERROR] 2018-04-19 00:39:44 Couldn't find a PNG file.
[DEBUG] 2018-04-19 00:39:44 Create new backup folder for Franz
[DEBUG] 2018-04-19 00:39:44 Creating directory: /home/jibran666/.config/Hardcode-Tray/Franz/2018-04-19 00:39:44/
[DEBUG] 2018-04-19 00:39:44 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/franz-panel.svg /tmp/tmp20aib95o
[DEBUG] 2018-04-19 00:39:46 Backup file: /tmp/files|assets|files|images|files|tray|files|linux|files|tray.png to: /home/jibran666/.config/Hardcode-Tray/Franz/2018-04-19 00:39:44/files|assets|files|images|files|tray|files|linux|files|tray.png
[DEBUG] 2018-04-19 00:39:46 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/franz-panel.svg /tmp/tmp1gioxcjl
[DEBUG] 2018-04-19 00:39:47 Backup file: /tmp/files|assets|files|images|files|tray|files|linux|files|tray@2x.png to: /home/jibran666/.config/Hardcode-Tray/Franz/2018-04-19 00:39:44/files|assets|files|images|files|tray|files|linux|files|tray@2x.png
[DEBUG] 2018-04-19 00:39:47 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/franz-attention-panel.svg /tmp/tmpefd97b_r
[DEBUG] 2018-04-19 00:39:48 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/franz-attention-panel.svg /tmp/tmp0zvi8x2_
[DEBUG] 2018-04-19 00:39:49 Backup file: /tmp/files|assets|files|images|files|tray|files|linux|files|tray-unread.png to: /home/jibran666/.config/Hardcode-Tray/Franz/2018-04-19 00:39:44/files|assets|files|images|files|tray|files|linux|files|tray-unread.png
[DEBUG] 2018-04-19 00:39:49 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/franz-attention-panel.svg /tmp/tmpe7izj0h6
[DEBUG] 2018-04-19 00:39:50 Backup file: /tmp/files|assets|files|images|files|tray|files|linux|files|tray-unread@2x.png to: /home/jibran666/.config/Hardcode-Tray/Franz/2018-04-19 00:39:44/files|assets|files|images|files|tray|files|linux|files|tray-unread@2x.png
[DEBUG] 2018-04-19 00:39:50 Create new backup folder for Google Chrome
[DEBUG] 2018-04-19 00:39:50 Creating directory: /home/jibran666/.config/Hardcode-Tray/Google Chrome/2018-04-19 00:39:50/
[DEBUG] 2018-04-19 00:39:50 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/google-chrome-tray.svg /tmp/tmpnyq564dc
[ERROR] 2018-04-19 00:39:52 Couldn't find a PNG file.
[DEBUG] 2018-04-19 00:39:52 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/google-chrome-tray.svg /tmp/tmpk5f4qfz1
[DEBUG] 2018-04-19 00:39:52 Backup file: /tmp/10153 to: /home/jibran666/.config/Hardcode-Tray/Google Chrome/2018-04-19 00:39:50/10153
[DEBUG] 2018-04-19 00:39:52 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/google-chrome-tray.svg /tmp/tmp5c6_84ev
[DEBUG] 2018-04-19 00:39:52 Backup file: /tmp/10154 to: /home/jibran666/.config/Hardcode-Tray/Google Chrome/2018-04-19 00:39:50/10154
[DEBUG] 2018-04-19 00:39:52 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/google-chrome-tray.svg /tmp/tmp34vk4hjw
[ERROR] 2018-04-19 00:39:52 Couldn't find a PNG file.
[DEBUG] 2018-04-19 00:39:52 Create new backup folder for Liferea
[DEBUG] 2018-04-19 00:39:52 Creating directory: /home/jibran666/.config/Hardcode-Tray/Liferea/2018-04-19 00:39:52/
[DEBUG] 2018-04-19 00:39:52 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/liferea-unread.svg /usr/share/pixmaps/unread.png
[DEBUG] 2018-04-19 00:39:52 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/liferea-available.svg /usr/share/pixmaps/available.png
[DEBUG] 2018-04-19 00:39:52 Backup file: /usr/share/liferea/pixmaps/unread.png to: /home/jibran666/.config/Hardcode-Tray/Liferea/2018-04-19 00:39:52/unread.png
[DEBUG] 2018-04-19 00:39:52 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/liferea-unread.svg /usr/share/liferea/pixmaps/unread.png
[DEBUG] 2018-04-19 00:39:52 Backup file: /usr/share/liferea/pixmaps/available.png to: /home/jibran666/.config/Hardcode-Tray/Liferea/2018-04-19 00:39:52/available.png
[DEBUG] 2018-04-19 00:39:52 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/liferea-available.svg /usr/share/liferea/pixmaps/available.png
[DEBUG] 2018-04-19 00:39:52 Create new backup folder for Messenger
[DEBUG] 2018-04-19 00:39:52 Creating directory: /home/jibran666/.config/Hardcode-Tray/Messenger/2018-04-19 00:39:52/
[DEBUG] 2018-04-19 00:39:52 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/messenger-indicator.svg /tmp/tmp4s__iwl6
[DEBUG] 2018-04-19 00:39:53 Backup file: /tmp/files|images|files|tray.png to: /home/jibran666/.config/Hardcode-Tray/Messenger/2018-04-19 00:39:52/files|images|files|tray.png
[DEBUG] 2018-04-19 00:39:53 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/messenger-indicator.svg /tmp/tmp5inh9ry9
[DEBUG] 2018-04-19 00:39:54 Backup file: /tmp/files|images|files|tray@2x.png to: /home/jibran666/.config/Hardcode-Tray/Messenger/2018-04-19 00:39:52/files|images|files|tray@2x.png
[DEBUG] 2018-04-19 00:39:54 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/messenger-indicator.svg /tmp/tmpxurr9bih
[DEBUG] 2018-04-19 00:39:54 Backup file: /tmp/files|images|files|tray@3x.png to: /home/jibran666/.config/Hardcode-Tray/Messenger/2018-04-19 00:39:52/files|images|files|tray@3x.png
[DEBUG] 2018-04-19 00:39:54 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/messenger-notification.svg /tmp/tmpvjev8cmr
[DEBUG] 2018-04-19 00:39:55 Backup file: /tmp/files|images|files|trayAlert.png to: /home/jibran666/.config/Hardcode-Tray/Messenger/2018-04-19 00:39:52/files|images|files|trayAlert.png
[DEBUG] 2018-04-19 00:39:55 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/messenger-notification.svg /tmp/tmpex9nyei6
[DEBUG] 2018-04-19 00:39:55 Backup file: /tmp/files|images|files|trayAlert@2x.png to: /home/jibran666/.config/Hardcode-Tray/Messenger/2018-04-19 00:39:52/files|images|files|trayAlert@2x.png
[DEBUG] 2018-04-19 00:39:55 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/messenger-notification.svg /tmp/tmpnt9y35ru
[DEBUG] 2018-04-19 00:39:56 Backup file: /tmp/files|images|files|trayAlert@3x.png to: /home/jibran666/.config/Hardcode-Tray/Messenger/2018-04-19 00:39:52/files|images|files|trayAlert@3x.png
[DEBUG] 2018-04-19 00:39:56 Create new backup folder for Skype
[DEBUG] 2018-04-19 00:39:56 Creating directory: /home/jibran666/.config/Hardcode-Tray/Skype/2018-04-19 00:39:56/
[DEBUG] 2018-04-19 00:39:56 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/skype-status-disturb.svg /tmp/tmpel1rs_8w
[DEBUG] 2018-04-19 00:39:56 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/skype-status-disturb.svg /tmp/tmpw32x6ekd
[DEBUG] 2018-04-19 00:39:57 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/skype-status-disturb-notification.svg /tmp/tmpt_dit73e
[DEBUG] 2018-04-19 00:39:57 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/skype-status-away.svg /tmp/tmpxxs89iew
[DEBUG] 2018-04-19 00:39:57 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/skype-status-away.svg /tmp/tmp3qbg5n6d
[DEBUG] 2018-04-19 00:39:57 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/skype-status-away-notification.svg /tmp/tmp7g8tbn_d
[DEBUG] 2018-04-19 00:39:57 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/skype-status-offline.svg /tmp/tmpyak69t4z
[DEBUG] 2018-04-19 00:39:57 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/skype-status-offline.svg /tmp/tmpe9ib6sf7
[DEBUG] 2018-04-19 00:39:57 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/skype-status-connected.svg /tmp/tmpe5aknf_k
[DEBUG] 2018-04-19 00:39:57 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/skype-status-connected.svg /tmp/tmpeu761ymc
[DEBUG] 2018-04-19 00:39:57 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/skype-status-connected-notification.svg /tmp/tmpq_z2_h76
[DEBUG] 2018-04-19 00:39:57 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/skype-indicator.svg /tmp/tmpq_ev72b2
[DEBUG] 2018-04-19 00:39:57 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/skype-status-hidden.svg /tmp/tmp_hug3awc
[DEBUG] 2018-04-19 00:39:57 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/skype-status-hidden.svg /tmp/tmp20g269g6
[DEBUG] 2018-04-19 00:39:57 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/skype-status-hidden-notification.svg /tmp/tmpy4lser6t
[DEBUG] 2018-04-19 00:39:57 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/skype-status-disturb.svg /tmp/tmpzxs7qgka
[DEBUG] 2018-04-19 00:39:57 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/skype-status-disturb.svg /tmp/tmp9nxdjt_h
[DEBUG] 2018-04-19 00:39:57 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/skype-status-disturb-notification.svg /tmp/tmpgde0qla0
[DEBUG] 2018-04-19 00:39:57 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/skype-status-away.svg /tmp/tmp008l42r5
[DEBUG] 2018-04-19 00:39:57 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/skype-status-away.svg /tmp/tmpwvdhvde_
[DEBUG] 2018-04-19 00:39:57 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/skype-status-away-notification.svg /tmp/tmpcg2gx4_g
[DEBUG] 2018-04-19 00:39:57 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/skype-status-offline.svg /tmp/tmpewvzw_gv
[DEBUG] 2018-04-19 00:39:57 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/skype-status-offline.svg /tmp/tmp8ba1qezo
[DEBUG] 2018-04-19 00:39:57 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/skype-status-connected.svg /tmp/tmp_rldhdhd
[DEBUG] 2018-04-19 00:39:57 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/skype-status-connected.svg /tmp/tmpozti6ltb
[DEBUG] 2018-04-19 00:39:57 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/skype-status-connected-notification.svg /tmp/tmpj6yqsc39
[DEBUG] 2018-04-19 00:39:57 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/skype-indicator.svg /tmp/tmp6a44zen5
[DEBUG] 2018-04-19 00:39:57 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/skype-status-hidden.svg /tmp/tmphhhiwnx0
[DEBUG] 2018-04-19 00:39:57 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/skype-status-hidden.svg /tmp/tmps11irb30
[DEBUG] 2018-04-19 00:39:57 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/skype-status-hidden-notification.svg /tmp/tmpundovi25
[DEBUG] 2018-04-19 00:39:57 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/skype-status-offline.svg /tmp/tmpp0i3lu83
[DEBUG] 2018-04-19 00:39:58 Backup file: /tmp/files|images|files|tray|files|linux|files|tray-offlineTemplate.png to: /home/jibran666/.config/Hardcode-Tray/Skype/2018-04-19 00:39:56/files|images|files|tray|files|linux|files|tray-offlineTemplate.png
[DEBUG] 2018-04-19 00:39:58 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/skype-status-offline.svg /tmp/tmp0x26qt5z
[DEBUG] 2018-04-19 00:39:59 Backup file: /tmp/files|images|files|tray|files|linux|files|tray-offlineTemplate@2x.png to: /home/jibran666/.config/Hardcode-Tray/Skype/2018-04-19 00:39:56/files|images|files|tray|files|linux|files|tray-offlineTemplate@2x.png
[DEBUG] 2018-04-19 00:39:59 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/skype-status-offline-notification.svg /tmp/tmpjdeh67yf
[DEBUG] 2018-04-19 00:40:00 Backup file: /tmp/files|images|files|tray|files|linux|files|tray-offlineUnreadTemplate.png to: /home/jibran666/.config/Hardcode-Tray/Skype/2018-04-19 00:39:56/files|images|files|tray|files|linux|files|tray-offlineUnreadTemplate.png
[DEBUG] 2018-04-19 00:40:00 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/skype-status-offline-notification.svg /tmp/tmpw167ml8w
[DEBUG] 2018-04-19 00:40:01 Backup file: /tmp/files|images|files|tray|files|linux|files|tray-offlineUnreadTemplate@2x.png to: /home/jibran666/.config/Hardcode-Tray/Skype/2018-04-19 00:39:56/files|images|files|tray|files|linux|files|tray-offlineUnreadTemplate@2x.png
[DEBUG] 2018-04-19 00:40:01 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/skype-status-connected.svg /tmp/tmpd_fenxzv
[DEBUG] 2018-04-19 00:40:02 Backup file: /tmp/files|images|files|tray|files|linux|files|tray-onlineTemplate.png to: /home/jibran666/.config/Hardcode-Tray/Skype/2018-04-19 00:39:56/files|images|files|tray|files|linux|files|tray-onlineTemplate.png
[DEBUG] 2018-04-19 00:40:02 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/skype-status-connected.svg /tmp/tmppngjhl71
[DEBUG] 2018-04-19 00:40:03 Backup file: /tmp/files|images|files|tray|files|linux|files|tray-onlineTemplate@2x.png to: /home/jibran666/.config/Hardcode-Tray/Skype/2018-04-19 00:39:56/files|images|files|tray|files|linux|files|tray-onlineTemplate@2x.png
[DEBUG] 2018-04-19 00:40:03 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/skype-status-connected-notification.svg /tmp/tmphn5iksnf
[DEBUG] 2018-04-19 00:40:03 Backup file: /tmp/files|images|files|tray|files|linux|files|tray-onlineUnreadTemplate.png to: /home/jibran666/.config/Hardcode-Tray/Skype/2018-04-19 00:39:56/files|images|files|tray|files|linux|files|tray-onlineUnreadTemplate.png
[DEBUG] 2018-04-19 00:40:03 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/skype-status-connected-notification.svg /tmp/tmpv2w9kl_r
[DEBUG] 2018-04-19 00:40:04 Backup file: /tmp/files|images|files|tray|files|linux|files|tray-onlineUnreadTemplate@2x.png to: /home/jibran666/.config/Hardcode-Tray/Skype/2018-04-19 00:39:56/files|images|files|tray|files|linux|files|tray-onlineUnreadTemplate@2x.png
[DEBUG] 2018-04-19 00:40:04 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/skype-status-disturb.svg /tmp/tmp4xboxl6u
[DEBUG] 2018-04-19 00:40:05 Backup file: /tmp/files|images|files|tray|files|linux|files|tray-donotdisturbTemplate.png to: /home/jibran666/.config/Hardcode-Tray/Skype/2018-04-19 00:39:56/files|images|files|tray|files|linux|files|tray-donotdisturbTemplate.png
[DEBUG] 2018-04-19 00:40:05 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/skype-status-disturb.svg /tmp/tmpzdqv4tfl
[DEBUG] 2018-04-19 00:40:07 Backup file: /tmp/files|images|files|tray|files|linux|files|tray-donotdisturbTemplate@2x.png to: /home/jibran666/.config/Hardcode-Tray/Skype/2018-04-19 00:39:56/files|images|files|tray|files|linux|files|tray-donotdisturbTemplate@2x.png
[DEBUG] 2018-04-19 00:40:07 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/skype-status-disturb-notification.svg /tmp/tmp5y65s4gn
[DEBUG] 2018-04-19 00:40:08 Backup file: /tmp/files|images|files|tray|files|linux|files|tray-donotdisturbUnreadTemplate.png to: /home/jibran666/.config/Hardcode-Tray/Skype/2018-04-19 00:39:56/files|images|files|tray|files|linux|files|tray-donotdisturbUnreadTemplate.png
[DEBUG] 2018-04-19 00:40:08 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/skype-status-disturb-notification.svg /tmp/tmpczr1l5eq
[DEBUG] 2018-04-19 00:40:09 Backup file: /tmp/files|images|files|tray|files|linux|files|tray-donotdisturbUnreadTemplate@2x.png to: /home/jibran666/.config/Hardcode-Tray/Skype/2018-04-19 00:39:56/files|images|files|tray|files|linux|files|tray-donotdisturbUnreadTemplate@2x.png
[DEBUG] 2018-04-19 00:40:09 Create new backup folder for WebTorrent Desktop
[DEBUG] 2018-04-19 00:40:09 Creating directory: /home/jibran666/.config/Hardcode-Tray/WebTorrent Desktop/2018-04-19 00:40:09/
[DEBUG] 2018-04-19 00:40:09 Backup file: /opt/webtorrent-desktop/resources/app.asar.unpacked/static/WebTorrent.png to: /home/jibran666/.config/Hardcode-Tray/WebTorrent Desktop/2018-04-19 00:40:09/WebTorrent.png
[DEBUG] 2018-04-19 00:40:09 Executing command: convert -background none -resize 22x22 /usr/share/icons/Papirus-Dark/22x22/panel/webtorrent-desktop-panel.svg /opt/webtorrent-desktop/resources/app.asar.unpacked/static/WebTorrent.png

**Comment by BlueManCZ** [comment]
I have the same problem on Debian 10. Nothing change after conversion.

**Comment by bilelmoussaoui** [comment]
Can you guys please provide the list of the applications that were supposed to be fixed and the specific version number too?

**Comment by BlueManCZ** [comment]
Emm, I think it would be useless, because hardcode-tray doesn't convert any icon for me. It seems like it doesn't work. There are still old icons. (Now I see it's maybe a bit off-topic). Maybe because of _testing distribution_? (Debian 10)
But I remember that it worked before. On Debian 9.

**Comment by bilelmoussaoui** [comment]
It doesn't work won't help me much. Which applications you want to fix using hardcode-tray?

**Comment by BlueManCZ** [comment]
Ou, yes, sorry.
I tried it now, and Mailspring, Discord and Clementine have still old icon.
![screenshot_20180525_164513](https://user-images.githubusercontent.com/17854950/40550652-039bd394-603b-11e8-9776-7d517d0c94df.png)
With dark theme it looks much better.
![screenshot_20180525_164732](https://user-images.githubusercontent.com/17854950/40550777-64baac7c-603b-11e8-98e3-aa754275b0e8.png)
But still old icons I think.. (Clementime probably use default icon for dark theme).

**Comment by bilelmoussaoui** [comment]
There's an open issue for discord. Mailspring was already fixed on master. Clémentine dosen't use a hardcoded tray icon

**Comment by BlueManCZ** [comment]
Ok, Thank you.
When I use hardcode-tray, Clementine is in output as transformed between Chromium and Discord.
> Clémentine dosen't use a hardcoded tray icon

So why it's there?
I'll try master for Mailspring.
Fortunately Discord default icon looks quite well in dark theme.

**Comment by bilelmoussaoui** [comment]
I forgot to remove it. We thought it's hardcoded but it's just a fallback.

**Comment by bilelmoussaoui** [comment]
Mailspring is fixed on master and there's an issue about the latest version of Discord. Closing.
