### ISSUE TITLE
 Ao support

### ISSUE THREAD

**Issue by jeremyj** [bilelmoussaoui/Hardcode-Tray#516]
Hello,
I would like to add the following apps:
Insync (https://www.insynchq.com/)
Ao (https://github.com/klauscfhq/ao)

Thanks!

**Comment by bilelmoussaoui** [comment]
Insync is already supported. Can I have the output of `sudo -E hardcode-tray --apply --only insync`?

**Comment by bilelmoussaoui** [comment]
Any news?

**Comment by bilelmoussaoui** [comment]
The Ao is not supported yet.
