### ISSUE TITLE
Ubuntu 18.04 PPA support

### ISSUE THREAD

**Issue by mokhosh** [bilelmoussaoui/Hardcode-Tray#518]
- Distribution : `ubuntu 18 beta`
i ran the 3 lines in the readme but i get this error:

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package hardcode-tray

```

**Comment by jibran666** [comment]
you can not install it from PPA because they do not support version 17.10+. you have to compile it from source.

**Comment by bilelmoussaoui** [comment]
The PPA doesn't build for the latest Ubuntu release. I would love to fix that but im so busy right now :(

**Comment by bilelmoussaoui** [comment]
@wa4557 Can you check this one when you have some free time? It seems that I can't request a build into the same archive we are using currently

**Comment by varlesh** [comment]
@wa4557 Import Filed
![image](https://user-images.githubusercontent.com/8083855/40103521-c6ec96f6-58fe-11e8-8c64-6e7d3299caf8.png)

**Comment by varlesh** [comment]
PPA not updated daily and not use actual version.

**Comment by wa4557** [comment]
It seems it's a bug with launchpad: https://bugs.launchpad.net/bzr-git/+bug/1313861
Not sure how to fix that

**Comment by bilelmoussaoui** [comment]
Closing this in favour of https://github.com/bilelmoussaoui/Hardcode-Tray/issues/494
Which will provide us an easy way to package the script into almost every distro without having to deal with each one whenever we push a new update.
