### ISSUE TITLE
pCloud support

### ISSUE THREAD

**Issue by 7im4pple** [bilelmoussaoui/Hardcode-Tray#524]
add pcloud to supported apps.
thanks

**Comment by bilelmoussaoui** [comment]
How did you installed pcloud? the only available version is an appimage binary file. And we can't patch those "sandboxed" packages yet.

**Comment by 7im4pple** [comment]
I see, I actually do it through the AUR.. but that may just be doing the app image for me..not sure.

**Comment by bilelmoussaoui** [comment]
Can you please update this issue and the other one you've opened with the package name, or any information that could be useful

**Comment by arcanepanda** [comment]
Would really love it if pcloud could be patched.

**Comment by bilelmoussaoui** [comment]
Fixed on master.

**Comment by bilelmoussaoui** [comment]
I'm pretty busy those last days. I don't know when I can create a new release. There is a bunch of stuff that I would like to fix/improve before releasing a new version. 
You can use the master branch. Building is pretty simple!

**Comment by varlesh** [comment]
@arcanepanda
for temporary solution you can download config file to database:
```
cd /usr/share/hardcode-tray/database/
sudo wget https://raw.githubusercontent.com/bilelmoussaoui/Hardcode-Tray/master/data/database/pcloud-drive.json
sudo -E hardcode-tray -ct RSVGConvert -o pcloud-drive
```

**Comment by arcanepanda** [comment]
@bilelmoussaoui  I understand, we will wait for the release, thanks again for maintaining this awesome app :)
@varlesh Thanks for the quick reply & the quick fix for now, I tried the solution, i get an error: 
** (hardcode-tray:21986): WARNING **: 08:34:23.317: Unable to connect to dbus: The connection is closed

This is the log file:
[DEBUG] 2018-08-23 08:34:23 DE: Mate
[DEBUG] 2018-08-23 08:34:23 Config file: Not found.
[DEBUG] 2018-08-23 08:34:23 Arguments/Icon Size: None
[DEBUG] 2018-08-23 08:34:23 System/Icon Size: 22
[DEBUG] 2018-08-23 08:34:23 System/Theme: Papirus-Adapta
[DEBUG] 2018-08-23 08:34:23 Arguments/Conversion Tool: RSVGConvert
[DEBUG] 2018-08-23 08:34:23 Arguments/Only: pcloud-drive

Thanks again :)
