### ISSUE TITLE
Riot/Riot Web support

### ISSUE THREAD

**Issue by varlesh** [bilelmoussaoui/Hardcode-Tray#525]
Application Riot (riot-web) A glossy Matrix collaboration client for the web. 
Official page: https://riot.im/desktop.html
GitHub page: https://github.com/vector-im/riot-web
Used Electron, but files unpacked.

- app_path: `/opt/Riot/`
- icons_path: `/opt/Riot/resources/app/img/`
- original tray icon name: `riot.png`
- theme tray icon name: `riot-tray`

https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/1282

**Comment by bilelmoussaoui** [comment]
Fixed by @varlesh

**Comment by varlesh** [comment]
@bilelmoussaoui Please reopen... application working very strange.
Initially when openned proggram load icon `riot.png`, BUT letter use ico format - icon `riot.ico`
It's possible convert on our tools?
![image](https://user-images.githubusercontent.com/8083855/40132597-48268778-594e-11e8-9032-5c9100734ddc.png)

**Comment by varlesh** [comment]
For example:
```
{
    "name": "Riot Web",
    "app_path": [
        "/opt/Riot/",
        "/usr/lib/riot/electron_app"
    ],
    "icons_path": [
        "/opt/Riot/resources/app/img/",
        "/usr/lib/riot/electron_app/img/"
    ],
    "icons": {
        "tray": {
            "original": "riot.png",
            "theme": "riot-tray"
        },
        "tray-ico": {
            "original": "riot.ico",
            "theme": "riot-tray"
        }
    }
}
```
/usr/lib/riot/electron_app - it's paths from aur package

**Comment by varlesh** [comment]
How this worked:
![peek 2018-05-16 21-27](https://user-images.githubusercontent.com/8083855/40133203-1b81c7ee-5950-11e8-8eb8-23eaf46e8f47.gif)

**Comment by varlesh** [comment]
It's not ico.... more info here:
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/1282

**Comment by varlesh** [comment]
i'm manually convert icon to ICO on Gimp, but icon not changed :(
![image](https://user-images.githubusercontent.com/8083855/40133737-a6cd30e4-5951-11e8-94a0-db5561e886d8.png)

**Comment by bilelmoussaoui** [comment]
Is the application open source?
