### ISSUE TITLE
not fixing vlc icon

### ISSUE THREAD

**Issue by exiele** [bilelmoussaoui/Hardcode-Tray#528]
### Specifications
- Hardcode-Tray version : 4.2
- Distribution : Solus (budgie)
- Gtk version : 3.22
- Inkscape version : 0.92.2
- Application name :  VLC (VideoLAN)
- Application version : 3.0.2

### Expected behavior and actual behavior
when I run `sudo -E hardcode-tray` it doesn't find and consequently doesn't fix the VLC tray icon.
![2018-05-17--13 16 58 537](https://user-images.githubusercontent.com/20567069/40190218-acd9c4f6-59d4-11e8-9c61-9495cae73da8.png)
 
### What I tried
- Ran `whereis vlc` to find all the installation folders and ran hardcode-tray with `--path` to all the locations
- Ran hardcode-tray with `--conversion-tool ImageMagick`

**Comment by bilelmoussaoui** [comment]
VLC is not supported and can not be fixed as the icon is hardcoded on the binary. There's no easy way to change that without compiling the application from source code. So, for me, just disable it.
