### ISSUE TITLE
GTK error

### ISSUE THREAD

**Issue by Rykoh** [bilelmoussaoui/Hardcode-Tray#529]
### Specifications
- Hardcode-Tray version : `3.5.2.1`
- Distribution : `Ubuntu 16.04`
- Inkscape version : `0.92.3`
- Sni-qt version: `0.2.7`
- Application name :  `Chrome; Mailspring; Discord`
- Application version : `66.0.3359.181-1; 1.2.1; 0.0.5`

Icons not changing, terminal also shows three errors:

sudo hardcode-tray -ct Inkscape -s 16 -a
Welcome to Hardcode-Tray!
Desktop Environment: **Other** (Should be Unity7)
Scaling Factor: 1
Icon Size: 16

**(hardcode-tray:21553): Gtk-WARNING** **: Theme parsing error: gtk-contained.css:27:19: Missing name of pseudo-class**

**(hardcode-tray:21553): Gtk-WARNING** **: Theme parsing error: gtk-contained.css:2780:55: Not a valid image**
Icon Theme: Papirus
Conversion Tool: Inkscape
To Do: All
Applying now..

Discord                    [############................................................] 1/3 33.3% 2.30s
Google Chrome       [########################........................] 2/3 66.7% 1.22s
Mailspring                [####################################] 3/3 100.0% 1.28s
Took 4.81s to finish the tasks

Done, Thank you for using the Hardcode-Tray fixer!

**Comment by bilelmoussaoui** [comment]
Those errors are related to your Gtk theme and has nothing to do with the script itself. You will get the same thing whenever you run anything that uses Gtk on terminal.

**Comment by Rykoh** [comment]
So thats not the reason why the icons are not changing?
