### ISSUE TITLE
Icon try size

### ISSUE THREAD

**Issue by ynnr85** [bilelmoussaoui/Hardcode-Tray#534]
### Specifications
- Hardcode-Tray version : `4.2`
- Distribution : `Kubuntu 18.04 Bionic`
- Gtk version : `3.22`
- Inkscape version : `0.92.3 (2405546, 2018-03-11)`
- Application name :  `Slack`
- Application version : `Direct Download 3.2.0-beta2 HEAD/5a7a50e 64-bit`

### Expected behavior and actual behavior

Icon size match all other icons in system try

### Steps to reproduce the problem
1. Download and install slack  deb package form official website.
2. Run `sudo -E hardcode-tray --conversion-tool Inkscape --size 22 --theme Papirus-Dark -o slack`
3. Output 

`Welcome to Hardcode-Tray!
Desktop Environment: Kde
Scaling Factor: 1
Icon Size: 22
Icon Theme: Papirus-Dark
Conversion Tool: Inkscape
To Do: Slack
1 - Apply
2 - Revert
3 - Clear Backup Cache
Please choose: 1
Applying now..

Slack               [####################################] 1/1 100.0% 0.73s
Took 0.73s to finish the tasks

Done, Thank you for using the Hardcode-Tray fixer!
`
4. Icon show this way, note that it is smaller than other icons (or it is the correct size?):
![image](https://user-images.githubusercontent.com/6003521/41015864-2da55880-691a-11e8-8c6c-ee74dae6df97.png)

How can I fix this problem?

**Comment by bilelmoussaoui** [comment]
You can use an other size using `--size` argument. See the documentation on the README file.
