### ISSUE TITLE
Wire-Desktop not being detected

### ISSUE THREAD

**Issue by 7im4pple** [bilelmoussaoui/Hardcode-Tray#536]
### Specifications
- Hardcode-Tray version : `4.2`
- Distribution : `KDE-Neon`
- Gtk version : `3.18`
- Inkscape version : `0.91` if installed
- Cairo version : `` if installed
- Sni-qt version: `2.7` if installed
- Application name :  `wire-desktop`
- Application version : `3.2.2840`

### Expected behavior and actual behavior
Hardcode tray doesn't seem to see wire application, isn't listed when applying. Using Papirus icon theme. I installed the wire .deb from their website. 

### Steps to reproduce the problem
1. 
2. 
3.

**Comment by bilelmoussaoui** [comment]
It's an issue with KDE. See the list of closed issues. You can try using an other icon size using `--size` argument. If you still have this issue please reopen.
