### ISSUE TITLE
GoldenDict support

### ISSUE THREAD

**Issue by raabf** [bilelmoussaoui/Hardcode-Tray#538]
It would be nice to see support for [GoldenDict](http://goldendict.org), a feature-rich dictionary lookup program.

![auswahl_020](https://user-images.githubusercontent.com/4788201/42819888-142dfcf0-89d5-11e8-9bf9-28e7ff91b37e.png)

[Sources](https://github.com/goldendict/goldendict)

Packages: [Debian](https://packages.debian.org/stretch/goldendict), [Ubuntu](https://packages.ubuntu.com/bionic/goldendict), [Fedora](https://apps.fedoraproject.org/packages/goldendict), [Arch](https://www.archlinux.org/packages/community/x86_64/goldendict/), [Suse](https://software.opensuse.org/package/goldendict)

Alternative Icons would be available; for example [Papirus](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/commit/a046cdd9690d147c851310a7bbedf34019e4a06f).

**Comment by varlesh** [comment]
icons used from theme:
```
trayIcon = new QSystemTrayIcon( QIcon::fromTheme("goldendict-tray", QIcon( ":/icons/programicon_old.png" )), this );
```
https://github.com/goldendict/goldendict/blob/master/mainwindow.cc#L593

```
QIcon::fromTheme("goldendict-scan-tray", QIcon( ":/icons/programicon_scan.png" )) :
```
https://github.com/goldendict/goldendict/blob/master/mainwindow.cc#L1135

**Comment by varlesh** [comment]
@raabf install git-version goldendict. It's will be fixed:
https://github.com/goldendict/goldendict/commit/eea6f686f6abc4735acb3edfdd1a88112c7b5f2f#diff-aa606ef6e49357e2b5a94103cd50666a

**Comment by bilelmoussaoui** [comment]
Thanks @varlesh for letting us know! fixed upstream

**Comment by varlesh** [comment]
thx @morealaz :)

**Comment by raabf** [comment]
Thanks the new goldendict version works like expected.
