### ISSUE TITLE
uGet support

### ISSUE THREAD

**Issue by thecountoftuscany** [bilelmoussaoui/Hardcode-Tray#539]
It would be nice to have `uGet` supported. It is one of the most popular download managers on Linux.
[uget](ugetdm.com)

Screenshot:
![uget-tray](https://user-images.githubusercontent.com/14308382/43057711-6ec317a0-8e61-11e8-990a-9e02105b1f98.png)

**Comment by varlesh** [comment]
uget not hardcoded and use system icons for tray:
```
uget-tray-default
uget-tray-downloading
uget-tray-error
```
