### ISSUE TITLE
Add support AnyDesk

### ISSUE THREAD

**Issue by nixway** [bilelmoussaoui/Hardcode-Tray#548]
### Specifications
- Hardcode-Tray version : `4.3`
- Distribution : `Debian Buster`
- Gtk version : `3.22`
- Inkscape version : `0.92.3`
- Application name :  `AnyDesk`
- Application version : `2.9.9`

### Expected behavior and actual behavior
No support for tray icon Anydesk.

**Comment by varlesh** [comment]
impossible, tray icon used from binary

**Comment by bilelmoussaoui** [comment]
> impossible, tray icon used from binary

Thanks for checking this out!
