### ISSUE TITLE
Megasync, Private Internet Access support

### ISSUE THREAD

**Issue by overkill22** [bilelmoussaoui/Hardcode-Tray#549]
- Hardcode-Tray version : `4.2`
- Distribution : `Linux Mint 19`
- Gtk version : `3.22`
- ImageMagick : `6.9.7`
- Application name :  `MegaSync, Private Internet Access (PIA)`
- Application version : `MegaSync: 3.7.1` `PIA: 81`

The icons of MegaSync and PIA are the original ones, not the white one following the theme. I used the command: `sudo -E hardcode-tray --conversion-tool ImageMagick --size 22 --theme Papirus`

With result

```
Desktop Environment: Cinnamon
Scaling Factor: 1
Icon Size: 22
Icon Theme: Papirus
Conversion Tool: ImageMagick
To Do: All
1 - Apply
2 - Revert
3 - Clear Backup Cache
Please choose: 1
Applying now..


Discord             [#######.............................] 1/5 20.0% 0.11s
Dropbox             [##############......................] 2/5 40.0% 0.11s
Google Chrome       [######################..............] 3/5 60.0% 0.13s
Megasync            [#############################.......] 4/5 80.0% 0.03s
Teamviewer          [####################################] 5/5 100.0% 0.00s
Took 0.37s to finish the tasks

Done, Thank you for using the Hardcode-Tray fixer!
```

However, the icons in the tray are still the original, even after reboot.

![46402665-00792900-c733-11e8-92c9-4318204d7134](https://user-images.githubusercontent.com/16596491/46447423-54782200-c7b4-11e8-9d16-b38fc6ce5896.jpg)
# #

**Comment by varlesh** [comment]
MegaSync worked fine with hardcode-tray:
![image](https://user-images.githubusercontent.com/8083855/57853064-d5d96d80-77f5-11e9-9bac-73c8cb30d43d.png)

**Comment by varlesh** [comment]
@overkill22 Official PIA Client used icons from binary:
![image](https://user-images.githubusercontent.com/8083855/57853924-0a4e2900-77f8-11e9-8412-b74b26c731cc.png)
https://www.privateinternetaccess.com/installer/x/download_installer_linux

**Comment by bilelmoussaoui** [comment]
PIA is a Qt app?

**Comment by varlesh** [comment]
@bilelmoussaoui yes, use QSystemTray

**Comment by bilelmoussaoui** [comment]
Well, they should fix that upstream then. Closing this as a duplicate for Megasync and upstream issue for PIA. Thank you @varlesh !
