### ISSUE TITLE
Provide an example configuration file

### ISSUE THREAD

**Issue by merlinschumacher** [bilelmoussaoui/Hardcode-Tray#550]
### Specifications
- Hardcode-Tray version : `4.3`
- Distribution : `Antergos`
- Gtk version : `3.24`
- Inkscape version : `` if installed
- Cairo version : `1.15.14` if installed
- Sni-qt version: `0.2.6` if installed
- Application name :  ``
- Application version : ``

### Expected behavior and actual behavior
I expected an example for the hardcode-tray.json. None is provided.

**Comment by bilelmoussaoui** [comment]
It's provided here https://github.com/bilelmoussaoui/Hardcode-Tray/blob/master/data/config.json
Just take a look at the readme file.
