### ISSUE TITLE
VeraCrypt support

### ISSUE THREAD

**Issue by mindbound** [bilelmoussaoui/Hardcode-Tray#551]
[VeraCrypt](https://www.veracrypt.fr/en/Home.html) currently has a tray icon that doesn't quite fit in any theme (first icon from the right):
![screenshot_2018-10-16_01-32-48](https://user-images.githubusercontent.com/1147991/46982036-6ffff880-d0e3-11e8-8dc2-31ec426e1be1.png)

Could it be possible to add VeraCrypt to the list of supported software? TIA.

**Comment by varlesh** [comment]
VeraCrypt with panel suffix name used icon for tray from current icon theme... veracrypt-panel

**Comment by bilelmoussaoui** [comment]
Thanks @varlesh for checking this one.

**Comment by FadeMind** [comment]
@varlesh in KDE Plasma Veracrypt does not follow `panel/veracrypt-panel.svg` and using standard icon.
![Screenshot_20200512_074011](https://user-images.githubusercontent.com/9846948/81642506-d403b380-9423-11ea-930e-f1a29d15d80d.png)
```
pacman -Ql veracrypt 
veracrypt /usr/
veracrypt /usr/bin/
veracrypt /usr/bin/veracrypt
veracrypt /usr/share/
veracrypt /usr/share/applications/
veracrypt /usr/share/applications/veracrypt.desktop
veracrypt /usr/share/licenses/
veracrypt /usr/share/licenses/veracrypt/
veracrypt /usr/share/licenses/veracrypt/License.txt
veracrypt /usr/share/pixmaps/
veracrypt /usr/share/pixmaps/veracrypt.xpm
```
:thinking:

**Comment by varlesh** [comment]
Now icon on binary

**Comment by FadeMind** [comment]
yep, and same is in Jdownloader2 too (even if HT applying patch)
