### ISSUE TITLE
"Franz" broken

### ISSUE THREAD

**Issue by pat-s** [bilelmoussaoui/Hardcode-Tray#553]
### Specifications
- Hardcode-Tray version : `4.3`
- Distribution : `Arch`
- Gtk version : ``
- Inkscape version : `0.92.3` if installed
- Cairo version : `1.16` if installed
- Sni-qt version: `0.2.6` if installed
- Application name :  `Franz`
- Application version : `5.0.0_beta.18`

### Expected behavior and actual behavior

Applying the script has no effect anymore. 
Probably because the paths of Franz have changed (not anymore under `/opt/Franz`.

I am on Arch KDE and usually using the following script: `sudo -E hardcode-tray --conversion-tool RSVGConvert --size 22 --theme Papirus`

**Comment by bilelmoussaoui** [comment]
They must have changed something other than just the path. will look into this asap.

**Comment by varlesh** [comment]
New paths on packed asar (`/opt/Franz/resources/`) on DEB 5.0.0_beta.18:
```
assets/images/tray/linux/tray.png
assets/images/tray/linux/tray@2x.png
assets/images/tray/linux/tray-unread.png
assets/images/tray/linux/tray-unread@2x.png
```

**Comment by varlesh** [comment]
Gitify & Franz removed from database, because crashed Hardcode-Tray.
#646 #637
