### ISSUE TITLE
Rambox (snap package) not detected

### ISSUE THREAD

**Issue by mlms13** [bilelmoussaoui/Hardcode-Tray#557]
### Specifications
- Hardcode-Tray version : `4.2`
- Distribution : `Ubuntu 18.04`
- Gtk version : `3.22`
- Sni-qt version: `0.2.7+20161212~11~ubuntu18.04.1`
- Application name :  `Rambox`
- Application version : `0.6.3`

I can't seem to get HC-T to detect Rambox. I saw in closed tickets that the application may need to be not running for the script to work, so I've ensured (via quitting the app and `killall rambox`) that Rambox isn't currently running.

When I run a normal `--apply`, it finds several apps and seems to work:

```
~ ❯ sudo -E hardcode-tray --apply
Welcome to Hardcode-Tray!
Desktop Environment: Other
Scaling Factor: 1
Icon Size: 22
Icon Theme: Papirus-Dark
Conversion Tool: RSVGConvert
To Do: All
Applying now..


Dropbox             [######..............................] 1/6 16.7% 0.05s
Google Chrome       [############........................] 2/6 33.3% 0.10s
Google Play Music Desktop Player            [##################..................] 3/6 50.0% 1.02s
Keybase             [########################............] 4/6 66.7% 0.14s
Slack               [##############################......] 5/6 83.3% 0.04s
Steam               [####################################] 6/6 100.0% 0.01s
Took 1.36s to finish the tasks
```

When I run with `--apply --only rambox`, the script reports `No apps to fix!`

**Comment by varlesh** [comment]
snap not support icon themes and hardcode-tray too...
Use deb

**Comment by bilelmoussaoui** [comment]
Snap packages are not my priority right now. If anyone wants to fix them, they can open a PR and I will happily  review it and merge it.

For now I'm going to close this as it's out of the focus of the project.
