### ISSUE TITLE
I would like to know if Suru++ is compatible with this script

### ISSUE THREAD

**Issue by gusbemacbe** [bilelmoussaoui/Hardcode-Tray#565]
Hello @bilelmoussaoui.

I would like to know if [Suru++ 25](https://github.com/gusbemacbe/suru-plus) is compatible with this script.

Observe that the folders 22 and 24 are symlinks.

**Comment by bilelmoussaoui** [comment]
It's quite the opposite question you should ask, is Suru++ compatible with Hardcode-Tray. It's up to the theme to add the new icon names for each hardcoded application out there. It seems that Suru++ has few of them; you can send a MR to add a screenshot like it's done with Numix & Papirus if you want.
