### ISSUE TITLE
Icons small and blurry in KDE Plasma with 4K monitor

### ISSUE THREAD

**Issue by mvolf** [bilelmoussaoui/Hardcode-Tray#566]
### Specifications
- Hardcode-Tray version : `4.3`
- Distribution : `Arch linux`
- Gtk version : `3.24.5`
- Inkscape version : `0.92.4`
- Cairo version : `1.16`
- Sni-qt version: `sni-qt-patched-git from AUR`
- Application name :  `ALL`
- Application version : `ALL`

### Expected behavior and actual behavior
In KDE plasma all the icons changed by hardcode-tray are to small and still blurry.
Command used to apply the changes to icons: hardcode-tray --theme Papirus
Using other values for size don't make any difference.

Screenshot of icons (Slack and Franz in this case):
<img width="203" alt="tray" src="https://user-images.githubusercontent.com/798213/52720460-f223ff00-2fa7-11e9-9371-e2c5d456f48c.png">

**Comment by bilelmoussaoui** [comment]
You can try to set --size argument or change the scale factor in config file. Check the readme about that.

**Comment by mvolf** [comment]
As written in the first comment none of those arguments or config values make any difference. This could do something with the fact that KDE always uses 32px icons for tray (independent of scaling factor).

**Comment by mvolf** [comment]
I just tried setting scaling factor to 2 and using 16 for --size argument. The icons now have correct size, but are still blurry comparing with other icons from icon theme:

<img width="190" alt="tray" src="https://user-images.githubusercontent.com/798213/52724854-695d9100-2fb0-11e9-88ab-75df7781f650.png">

Any suggestions?

**Comment by bilelmoussaoui** [comment]
This might be related to the icon theme you're using too. KDE has always been doing some weird stuff with scaling factor and I don't use it to reproduce or try to figure out a way to fix it :( 
What is the output when you run hardcode-tray? copy paste everything.

**Comment by mvolf** [comment]
I'm using Papirus theme which is listed as a supported theme.
Here's the output:

`Welcome to Hardcode-Tray!
Hardcode-Tray replaces some icons on the binary files of some applications. 
Please close all the running applications before running Hardcode-Tray script.
Desktop Environment: Other
Scaling Factor: 2
Icon Size: 32
Icon Theme: Papirus
Conversion Tool: Inkscape
To Do: All
1 - Apply
2 - Revert
3 - Clear Backup Cache
Please choose: 1
Applying now..


Chromium            [####................................] 1/9 11.1% 0.28s
Dropbox             [########............................] 2/9 22.2% 2.76s
Franz               [############........................] 3/9 33.3% 2.98s
HP Printer          [################....................] 4/9 44.4% 0.29s
JDownloader         [########################............] 6/9 66.7% 0.56s
Skype               [############################........] 7/9 77.8% 22.32s
Slack               [################################....] 8/9 88.9% 0.71s
Solaar              [####################################] 9/9 100.0% 1.62s
Took 31.51s to finish the tasks

Done, Thank you for using the Hardcode-Tray fixer!
`

**Comment by bilelmoussaoui** [comment]
Yeah, give rsvg-convert a try.

**Comment by mvolf** [comment]
I don't see any difference with using RSVGConvert or any of the other tools for that matter:

<img width="174" alt="tray" src="https://user-images.githubusercontent.com/798213/52768937-2db5dc00-302f-11e9-8c26-237b9dcc7f20.png">

**Comment by varlesh** [comment]
@mvolf It's looking better as previos version.
For compare:
![image](https://user-images.githubusercontent.com/8083855/52769072-ad9c7000-3048-11e9-910b-cbbd5704e4d9.png)
![image](https://user-images.githubusercontent.com/8083855/52769130-cad13e80-3048-11e9-8afc-8f65a3852961.png)
Maybe try more size? Fore example 64px

**Comment by varlesh** [comment]
@mvolf Also not forgot for some application need run application with Unity DE option.
For example:
`XDG_CURRENT_DESKTOP=Unity wire-desktop`
Try it.

**Comment by mvolf** [comment]
@varlesh The second screenshot you posted is without hardcode-tray icons. That's why it's so bad. I'll try some other sizes and unity option.

**Comment by varlesh** [comment]
@mvolf  All libappindicator-apps blurred on KDE. It's KDE bug (or libappindicator). For fix that need use Unity DE option..
https://bugs.kde.org/show_bug.cgi?id=366062

**Comment by mvolf** [comment]
@varlesh 64 size looks terrible (used 16 for --size and 4 as a scaling factor to get 64):

<img width="182" alt="tray" src="https://user-images.githubusercontent.com/798213/52769495-bed98280-3030-11e9-9d5a-46db4242ddcb.png">

**Comment by varlesh** [comment]
@mvolf try 32px with unity option

**Comment by varlesh** [comment]
i mean 16px icon with 2 scale

**Comment by mvolf** [comment]
@varlesh I was already on 16px with 2 scale (that's the best looking screenshot). I'll try adding the unity option to .desktop files now.

**Comment by varlesh** [comment]
for test you can run from terminal only

**Comment by mvolf** [comment]
@varlesh I don't see any difference with using the unity option:
<img width="185" alt="tray" src="https://user-images.githubusercontent.com/798213/52769961-2e9c3d00-3032-11e9-92dc-ac7ec1fa7ca9.png">

I'm fine with this quality if there's nothing that can be done. I wanted to open the issue to verify that it's not some kind of a bug.

**Comment by varlesh** [comment]
@mvolf i don't know how help you, i'm not have 4K display and can not test it... Need experiment with scale, sizes... Also read this manual too:
https://wiki.archlinux.org/index.php/HiDPI#Tray_icons_with_fixed_size

PS: Unity option used for only libappindicator-apps (if libappindicator libs not used as dependencies, this option not needed)

**Comment by varlesh** [comment]
@mvolf Also you can run Qt5-application with tray and compare size and rendering... for example qbittorrent

**Comment by varlesh** [comment]
@mvolf My experiments on FullHD:
- package slack-desktop-3.3.7-amd64.deb
- KDE Neon Dev Edition
- KDE 5.15
Original icon:
![image](https://user-images.githubusercontent.com/8083855/52770850-aa57b300-304d-11e9-8cf3-a38a8a3b682a.png)
Original with Unity option:
![image](https://user-images.githubusercontent.com/8083855/52770909-d8d58e00-304d-11e9-85a7-ca9acab7d72f.png)
Fixed icon by Hardcode Tray (without Unity option, hm but this worked too...i think it's fixed on Electron):
![image](https://user-images.githubusercontent.com/8083855/52770976-0e7a7700-304e-11e9-8f02-31e0845487e2.png)
Fixed icon by Hardcode Tray (with Unity option):
![image](https://user-images.githubusercontent.com/8083855/52771041-3d90e880-304e-11e9-9ffc-168fb9d90f47.png)

**Comment by mvolf** [comment]
@varlesh Thanks for your help and effort. I also noticed that Unity option has no effect if hardcode tray fix is used.
Qt5 applications have a much higher quality icons (qbittorrent as an example):
<img width="223" alt="tray" src="https://user-images.githubusercontent.com/798213/52773287-e0d80280-303a-11e9-8b8d-4054996a7160.png">
 
It's obvious that a combination of libappindicator and KDE is the cause of this.
@bilelmoussaoui You can close this ticket as this is not a hardcode-tray issue.
Thanks for the help guys,

**Comment by bilelmoussaoui** [comment]
Thanks for keeping the discussion constructive. If there is anything that should be improved here, please let me know even if I don't have the time to work more on the script :)
