### ISSUE TITLE
skypeforlinux icon is blurry 

### ISSUE THREAD

**Issue by rgoomes** [bilelmoussaoui/Hardcode-Tray#567]
### Specifications
- Hardcode-Tray version : `4.3`
- Distribution : `KDE Neon`
- Gtk version : `3.22`
- Sni-qt version: `0.2.7+17.04.20170112-0ubuntu`
- Application name :  `skypeforlinux`
- Application version : `8.34.0.78`
- Theme: `Suru++`

### Expected behavior and actual behavior
Size 16
![](https://i.imgur.com/muhxrNa.png)

Size 22
![](https://i.imgur.com/k6duPvA.png)

### Steps to reproduce the problem
1. run `sudo -E hardcode-tray -a --conversion-tool RSVGConvert --size 16 --theme Suru++` or `sudo -E hardcode-tray -a --conversion-tool RSVGConvert --size 22 --theme Suru++`
2. open skypeforlinux
3. check indicator icon blurry

**Comment by rgoomes** [comment]
I found the problem. `apt install libappindicator3-1` fixes the blur

**Comment by bilelmoussaoui** [comment]
Thanks for sharing the tip! Added that to the README.
