### ISSUE TITLE
Add ElectronMail support

### ISSUE THREAD

**Issue by Faust30000** [bilelmoussaoui/Hardcode-Tray#577]
Add please app ElectronMail.
https://github.com/vladimiry/ElectronMail

**Comment by varlesh** [comment]
@Faust30000 How this worked? You can show screenshot with notification mail status?
on source code numbers draw as font:
```
const icon = appRelativePath("./assets/icons/icon.png");
    return Object.assign({ appDir,
        userDataDir,
        icon, trayIcon: icon, numbersFont: appRelativePath("./assets/numbers.ttf"), browserWindowPage: developmentEnv
```

**Comment by varlesh** [comment]
app used packed asar:
- icons path: `/opt/ElectronMail/resources/`
- icon: `app/assets/icons/icon.png`

**Comment by varlesh** [comment]
@Faust30000 It's badge used for tray?
![image](https://user-images.githubusercontent.com/8083855/55389086-9f95a680-5545-11e9-9b7d-08825fc41265.png)

**Comment by varlesh** [comment]
Papirus icon added:
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/commit/f83c1c8646d17591924b9c64385da63ddfef1f72
PR for hardcode-tray database:
https://github.com/bilelmoussaoui/Hardcode-Tray/pull/576/commits/e6e449bb9a64f55708a876dae4ccda4940519565

**Comment by bilelmoussaoui** [comment]
Fixed! Thank you @varlesh

**Comment by varlesh** [comment]
@Faust30000 
![image](https://user-images.githubusercontent.com/8083855/55390664-bb4e7c00-5548-11e9-955b-6850d03839b9.png)
But i'm not check notification icon, because not have  Proton account

**Comment by vladimiry** [comment]
You should not override the ElectronMail tray icon by a static one. It's actually gets rendered dynamically/programmatically. See https://github.com/vladimiry/ElectronMail/issues/464#issuecomment-974619885.
