### ISSUE TITLE
flameshot icon fails to fixed

### ISSUE THREAD

**Issue by yangdaweihit** [bilelmoussaoui/Hardcode-Tray#580]
My flameshot icon in system tray is like:

![image](https://user-images.githubusercontent.com/10682606/55660134-5be9b800-5837-11e9-8722-51c9d6fff591.png)

I have noticed that the same committed issue closed:

> _Originally posted by @bilelmoussaoui in https://github.com/bilelmoussaoui/Hardcode-Tray/issues/506#issuecomment-369536698_

But it seems that it do not work on my situation.

- Flameshot: 0.6.0-11 (Debian)
- Hardcode-Tray: 4.3
- Theme: Numix
- Running:
```
➜  ~ sudo hardcode-tray --only flameshot
[sudo] password for wall-e: 
Welcome to Hardcode-Tray!
Hardcode-Tray replaces some icons on the binary files of some applications. 
Please close all the running applications before running Hardcode-Tray script.
Desktop Environment: Other
Scaling Factor: 1
Icon Size: 22
Icon Theme: Numix
Conversion Tool: Inkscape
To Do: Flameshot
1 - Apply
2 - Revert
3 - Clear Backup Cache
Please choose: 1
Applying now..


No apps to fix!

Done, Thank you for using the Hardcode-Tray fixer!

```

**Comment by varlesh** [comment]
flameshot not hardcoded now and used icon `flameshot-tray` from current icon theme:
https://github.com/lupoDharkael/flameshot/blob/master/src/core/controller.cpp#L194
Open request on Numix

**Comment by bilelmoussaoui** [comment]
Thanks for your help @varlesh
