### ISSUE TITLE
Telegram

### ISSUE THREAD

**Issue by Slavvkko** [bilelmoussaoui/Hardcode-Tray#581]
### Specifications
- Hardcode-Tray version : `4.3`
- Distribution : `Arch`
- DE: `KDE`
- Gtk version : `3.24`
- Plasma desktop: `5.15.4-1`
- Inkscape version : `` if installed
- Cairo version : `` if installed
- Sni-qt version: `` if installed
- Application name :  `Telegram`
- Application version : `1.6.7-1`

### Expected behavior and actual behavior
Slack and Skypeforlinux applied good.
But telegram icon doesn't changed.

### Steps to reproduce the problem
`sudo -E hardcode-tray --conversion-tool RSVGConvert --size 22 --theme Papirus-Dark`
I also have installed  `libappindicator-gtk3`, without it no changed icon skype nor slack.

![k7SvWwJ](https://user-images.githubusercontent.com/1040652/56518397-05bf8900-6548-11e9-9d8c-d9bc784f311b.png)

**Comment by bilelmoussaoui** [comment]
How did you installed Telegram?

**Comment by Slavvkko** [comment]
From arch repository, [telegram-desktop](https://www.archlinux.org/packages/community/x86_64/telegram-desktop/) package

**Comment by yangdaweihit** [comment]
In my Numix theme also arises the same problem: 
![image](https://user-images.githubusercontent.com/10682606/56856341-3742b500-698b-11e9-99a2-2104d524b710.png)

**Comment by kuriot** [comment]
I've noticed that in `/home/riot/.local/share/TelegramDesktop/tdata/ticons/` Telegram icons are called `icon*.png` and Hardcode-Tray creates its icons with `ico*.png` (without "n"). I've tried to rename them by hand but it didn't help.

**Comment by varlesh** [comment]
Not confirm this, all worked fine:
- Telegram 1.7
- KDE Neon UE
- Hardcode-Tray 4.3-0~944+pkg3~ubuntu18.04.1

![Screenshot_20190515_092449](https://user-images.githubusercontent.com/8083855/57750531-b2c69500-76f3-11e9-8fbe-b1c11140cf51.png)

**Comment by varlesh** [comment]
@Slavvkko Need use fresh git version `hardcode-tray-git`, because recently added [PR](https://github.com/bilelmoussaoui/Hardcode-Tray/pull/559) for fix icon names.

**Comment by Slavvkko** [comment]
@varlesh hardcode-tray-git solve my problem, thank you!
