### ISSUE TITLE
Onboard

### ISSUE THREAD

**Issue by carmenfdezb** [bilelmoussaoui/Hardcode-Tray#584]
Could you please add onboard icon?

**Comment by varlesh** [comment]
sources, icon names, method?

**Comment by varlesh** [comment]
If you mean this: https://launchpad.net/onboard
Icon not hardcoded, used application icon for tray like as VLC and similar.
For Plasma i fix that on Materia Theme:
![image](https://user-images.githubusercontent.com/8083855/57751882-2cf91880-76f8-11e9-9700-6956c1ba95c3.png)

**Comment by carmenfdezb** [comment]
> If you mean this: https://launchpad.net/onboard
> Icon not hardcoded, used application icon for tray like as VLC and similar.
> For Plasma i fix that on Materia Theme:
> ![image](https://user-images.githubusercontent.com/8083855/57751882-2cf91880-76f8-11e9-9700-6956c1ba95c3.png)

I use Materia-theme with Numix-Square icons but onboard icon for tray is Numix-Square style and not Materia-theme style:

![captura_onboard](https://user-images.githubusercontent.com/6286776/57793688-3909c800-7742-11e9-9a22-9f36ea771ab2.png)

**Comment by varlesh** [comment]
@carmenfdezb update Materia theme from git and set appindicator method on settings:
![image](https://user-images.githubusercontent.com/8083855/57794289-5c3d7300-7754-11e9-84d4-ec7ea26e6f59.png)

**Comment by carmenfdezb** [comment]
> @carmenfdezb update Materia theme from git and set appindicator method on settings:
> ![image](https://user-images.githubusercontent.com/8083855/57794289-5c3d7300-7754-11e9-84d4-ec7ea26e6f59.png)

Thanks!! Now it works ;)

**Comment by carmenfdezb** [comment]
Sorry for contact you about this issue again, but I don't know how to solve it:
![Screenshot_20220106_145718](https://user-images.githubusercontent.com/6286776/148394302-786e11f5-a4dd-4bf5-b019-5764e90d2852.png)

Could you please help me? I use 'Arc Dark' as global theme, 'Material color' as plasma style and 'Papyrus-Dark' as icons on my PC with Fedora 35 KDE.

Thanks in advanced!

**Comment by varlesh** [comment]
Maybe you not install libappindicator? It's worked:
![image](https://user-images.githubusercontent.com/8083855/148484909-de4a470e-7bac-472d-a64c-7bb62599de34.png)

**Comment by varlesh** [comment]
or try run application with this variable:
`env XDG_CURRENT_DESKTOP=Unity onboard`

**Comment by carmenfdezb** [comment]
Thank you for your help, @varlesh! libappindicator was installed, but I remembered that libappindicator-gtk is needed:
https://github.com/Foundry376/Mailspring/issues/1207#issuecomment-489140946

So thank you so much!
