### ISSUE TITLE
teams-for-linux support

### ISSUE THREAD

**Issue by orange-buffalo** [bilelmoussaoui/Hardcode-Tray#595]
This is a request to support Electron wrapper for MS Teams: https://github.com/IsmaelMartinez/teams-for-linux

**Comment by varlesh** [comment]
added

**Comment by orange-buffalo** [comment]
Thanks a lot, @varlesh !

Just a question about visual consistency. With papirus-dark theme, notification budges have bluish appearance (for example, for Telegram app). But for teams-for-linux they are red (the same they were before this change):

![image](https://user-images.githubusercontent.com/4532247/64931805-49f85080-d87e-11e9-8c39-c0a9db7ac6a2.png)

Would it make sense to apply the same bluish styling for teams-for-linux?

**Comment by varlesh** [comment]
bluish styling draw from code i can't fix that

**Comment by orange-buffalo** [comment]
Got it, thanks
