### ISSUE TITLE
[Icon Request] Clipto Pro

### ISSUE THREAD

**Issue by yochananmarqos** [bilelmoussaoui/Hardcode-Tray#596]
I'd like to request [Clipto Pro](https://clipto.pro) if possible. It's an Electron app packaged as an AppImage. The PNG's are in `/squashfs-root/usr/share/icons/`.

![Screenshot from 2019-08-27 09-44-27](https://user-images.githubusercontent.com/5437803/63786498-6b81a000-c8af-11e9-8991-9a5fa8906eab.png)

**Comment by varlesh** [comment]
appimage - it's portable application. We not support this!
