### ISSUE TITLE
google-chrome and chromium after update doesn't work anymore

### ISSUE THREAD

**Issue by fajaryanw** [bilelmoussaoui/Hardcode-Tray#597]
### Specifications
- Hardcode-Tray version : `4.3`
- Distribution : `Arch Linux x86_64`
- Kernel : `5.2.13-arch1-1-ARCH`
- Desktop Environment : `GNOME 3.32.2`
- Gtk version : `3.24`
- Inkscape version : `0.92.4`
- Cairo version : `2.4.1`
- Sni-qt version: `0.2.7+17.04.20170112-1`
- RSVGConvert : `2.46.0`
- ImageMagick : `7.0.8.64-1`
- Application name :  `google-chrome` and `chromium`
- Application version : `77.0.3865.75-1` and `77.0.3865.75-1`

### Expected behavior and actual behavior
Expected : Icon change
Actual : tray icon does not change and become very small

![oke](https://user-images.githubusercontent.com/6999559/64688817-56179300-d4b7-11e9-9a63-faa3258b8edf.png)

### Steps to reproduce the problem
1. Before update `google-chrome` and `chromium`, tray icon is fine
2. After update `google-chrome` and `chromium` use command `yay -Syu`
3. I have run use various conversion tool like this
`sudo -E hardcode-tray --conversion-tool RSVGConvert --size 22 --theme Oranchelo`
`sudo -E hardcode-tray --conversion-tool Inkscape --size 22 --theme Oranchelo`
`sudo -E hardcode-tray --conversion-tool CairoSVG --size 22 --theme Oranchelo`
`sudo -E hardcode-tray --conversion-tool RSVGConvert --size 22 --theme Oranchelo`
`sudo -E hardcode-tray --conversion-tool ImageMagick --size 22 --theme Oranchelo`
but tray icon does not change and become very small

**Comment by varlesh** [comment]
updated
