### ISSUE TITLE
Whatsdesk support

### ISSUE THREAD

**Issue by HarDX** [bilelmoussaoui/Hardcode-Tray#598]
Can you support [whatsdesk](https://gitlab.com/zerkc/whatsdesk).

**Comment by varlesh** [comment]
Whatsdesk already supported:
https://github.com/bilelmoussaoui/Hardcode-Tray/blob/master/data/database/whatsdesk.electron.json
![image](https://user-images.githubusercontent.com/8083855/64923894-9ea0ba80-d7ef-11e9-9ba3-1a0c1b568794.png)

**Comment by varlesh** [comment]
Versions: **whatsdesk_0.2.18_amd64.deb** and hardcode-tray from git

**Comment by HarDX** [comment]
Hmm, can you paste cmd for it. with flag --only and Papirus icon.

**Comment by varlesh** [comment]
it's strange with flag --only not worked, but worked if fix all icons. I thinks it's problem with name Whats**D**esk... Need check it with lower key **d**

**Comment by varlesh** [comment]
worked with key `--only whatsdesk.electron`

**Comment by HarDX** [comment]
Ooo, cool worked without --only ). Thanks. But i often used --only... sorry for this issue )
