### ISSUE TITLE
[Icon request] Wicd

### ISSUE THREAD

**Issue by PonasKovas** [bilelmoussaoui/Hardcode-Tray#599]
I thought this package would have `wicd` supported, but it looks like it does not...

Am I the only person who uses `wicd` in the world?

**Comment by varlesh** [comment]
/usr/share/wicd/icons/hicolor/22x22/status/bad-signal-lock.png
/usr/share/wicd/icons/hicolor/22x22/status/bad-signal.png
/usr/share/wicd/icons/hicolor/22x22/status/both-bad-signal-lock.png
/usr/share/wicd/icons/hicolor/22x22/status/both-bad-signal.png
/usr/share/wicd/icons/hicolor/22x22/status/both-good-signal-lock.png
/usr/share/wicd/icons/hicolor/22x22/status/both-good-signal.png
/usr/share/wicd/icons/hicolor/22x22/status/both-high-signal-lock.png
/usr/share/wicd/icons/hicolor/22x22/status/both-high-signal.png
/usr/share/wicd/icons/hicolor/22x22/status/both-low-signal-lock.png
/usr/share/wicd/icons/hicolor/22x22/status/both-low-signal.png
/usr/share/wicd/icons/hicolor/22x22/status/good-signal-lock.png
/usr/share/wicd/icons/hicolor/22x22/status/good-signal.png
/usr/share/wicd/icons/hicolor/22x22/status/high-signal-lock.png
/usr/share/wicd/icons/hicolor/22x22/status/high-signal.png
/usr/share/wicd/icons/hicolor/22x22/status/idle-bad-signal-lock.png
/usr/share/wicd/icons/hicolor/22x22/status/idle-bad-signal.png
/usr/share/wicd/icons/hicolor/22x22/status/idle-good-signal-lock.png
/usr/share/wicd/icons/hicolor/22x22/status/idle-good-signal.png
/usr/share/wicd/icons/hicolor/22x22/status/idle-high-signal-lock.png
/usr/share/wicd/icons/hicolor/22x22/status/idle-high-signal.png
/usr/share/wicd/icons/hicolor/22x22/status/idle-low-signal-lock.png
/usr/share/wicd/icons/hicolor/22x22/status/idle-low-signal.png
/usr/share/wicd/icons/hicolor/22x22/status/low-signal-lock.png
/usr/share/wicd/icons/hicolor/22x22/status/low-signal.png
/usr/share/wicd/icons/hicolor/22x22/status/no-signal.png
/usr/share/wicd/icons/hicolor/22x22/status/receiving-bad-signal-lock.png
/usr/share/wicd/icons/hicolor/22x22/status/receiving-bad-signal.png
/usr/share/wicd/icons/hicolor/22x22/status/receiving-good-signal-lock.png
/usr/share/wicd/icons/hicolor/22x22/status/receiving-good-signal.png
/usr/share/wicd/icons/hicolor/22x22/status/receiving-high-signal-lock.png
/usr/share/wicd/icons/hicolor/22x22/status/receiving-high-signal.png
/usr/share/wicd/icons/hicolor/22x22/status/receiving-low-signal-lock.png
/usr/share/wicd/icons/hicolor/22x22/status/receiving-low-signal.png
/usr/share/wicd/icons/hicolor/22x22/status/signal-25.png
/usr/share/wicd/icons/hicolor/22x22/status/signal-50.png
/usr/share/wicd/icons/hicolor/22x22/status/signal-75.png
/usr/share/wicd/icons/hicolor/22x22/status/signal-100.png
/usr/share/wicd/icons/hicolor/22x22/status/transmitting-bad-signal-lock.png
/usr/share/wicd/icons/hicolor/22x22/status/transmitting-bad-signal.png
/usr/share/wicd/icons/hicolor/22x22/status/transmitting-good-signal-lock.png
/usr/share/wicd/icons/hicolor/22x22/status/transmitting-good-signal.png
/usr/share/wicd/icons/hicolor/22x22/status/transmitting-high-signal-lock.png
/usr/share/wicd/icons/hicolor/22x22/status/transmitting-high-signal.png
/usr/share/wicd/icons/hicolor/22x22/status/transmitting-low-signal-lock.png
/usr/share/wicd/icons/hicolor/22x22/status/transmitting-low-signal.png
/usr/share/wicd/icons/hicolor/22x22/status/wired.png
[status.tar.gz](https://github.com/bilelmoussaoui/Hardcode-Tray/files/3617322/status.tar.gz)

**Comment by varlesh** [comment]
https://git.launchpad.net/wicd/tree/gtk/wicd-client.py
