### ISSUE TITLE
Support Jami

### ISSUE THREAD

**Issue by HarDX** [bilelmoussaoui/Hardcode-Tray#600]
Can you add support Jami (Ring) Sip Client?

**Comment by varlesh** [comment]
As i know Jami not hardcoded and used current icon on tray from current icon theme with name `jami`.
If you use Plasma Theme with this icon, icon will be applied from plasma theme.
For example Materia KDE:
![image](https://user-images.githubusercontent.com/8083855/66047508-f2720a00-e538-11e9-926a-014fa10179fe.png)
