### ISSUE TITLE
rescuetime tray icon doesn't change

### ISSUE THREAD

**Issue by fajaryanw** [bilelmoussaoui/Hardcode-Tray#601]
### Specifications
- Hardcode-Tray version : `4.3` from package [hardcode-tray-git](https://aur.archlinux.org/pkgbase/hardcode-tray-git/)
- Distribution : `Arch Linux x86_64`
- Kernel : `5.3.1-arch1-1-ARCH`
- Desktop Environment : `GNOME 3.34.0`
- Icons : `Oranchelo`
- Gtk version : `3.24`
- Inkscape version : `0.92.4`
- Cairo version : `2.4.2`
- Sni-qt version: `0.2.7+17.04.20170112-1`
- RSVGConvert : `2.46.0`
- ImageMagick : `7.0.8-67`
- Application name :  `rescuetime`
- Application version : `2.14.5.2-1`

### Expected behavior and actual behavior
Expected : Icon change
Actual : tray icon does not change

### Steps to reproduce the problem
I've just installed rescuetime use `yay -S rescuetime2`
then I run various conversion tool like this
`sudo -E hardcode-tray --conversion-tool RSVGConvert --size 22 --theme Oranchelo`
`sudo -E hardcode-tray --conversion-tool Inkscape --size 22 --theme Oranchelo`
`sudo -E hardcode-tray --conversion-tool CairoSVG --size 22 --theme Oranchelo`
`sudo -E hardcode-tray --conversion-tool RSVGConvert --size 22 --theme Oranchelo`
`sudo -E hardcode-tray --conversion-tool ImageMagick --size 22 --theme Oranchelo`
and then restart but tray icon does not change

**Comment by varlesh** [comment]
@fajaryanw Earlier we support qt4-version with patched sni-qt. But mostly apps now migrated to Qt5 and we don't know how fix that, because new apps not use sni-qt.
https://aur.archlinux.org/cgit/aur.git/commit/PKGBUILD?h=rescuetime2&id=2a2446f5e2f5a8fbeedc51282709e0dde7cee26c
