### ISSUE TITLE
Error on Fedora

### ISSUE THREAD

**Issue by serovar** [bilelmoussaoui/Hardcode-Tray#603]
### Specifications
- Hardcode-Tray version : `4.3.r42`, installed from the Fedora repo.
- Distribution : `Fedora`
- Gtk version : `3.24.11`
- Cairo version : `1.16.0`
- Sni-qt version: `0.2.7`

### Expected behavior and actual behavior
sudo hardcode-tray --apply
No protocol specified
Unable to init server: Could not connect: Connection refused
No protocol specified
Unable to init server: Could not connect: Connection refused
Welcome to Hardcode-Tray!
Hardcode-Tray replaces some icons on the binary files of some applications. 
Please close all the running applications before running Hardcode-Tray script.
Desktop Environment: Other
Scaling Factor: 1
Icon Size: 22
Traceback (most recent call last):
  File "/usr/bin/hardcode-tray", line 103, in <module>
    if not isinstance(App.theme(), dict):
  File "/usr/lib/python3.7/site-packages/HardcodeTray/app.py", line 177, in theme
    theme = App.get("theme")
  File "/usr/lib/python3.7/site-packages/HardcodeTray/app.py", line 77, in get
    value = method()
  File "/usr/lib/python3.7/site-packages/HardcodeTray/modules/config/system.py", line 67, in theme
    theme_name = Gtk.Settings.get_default().get_property("gtk-icon-theme-name")
AttributeError: 'NoneType' object has no attribute 'get_property'

### Steps to reproduce the problem
1. Install the package from the repo on Fedora
2. sudo hardcode-tray --apply

**Comment by varlesh** [comment]
What you theme use?
try it:
`sudo -E hardcode-tray --conversion-tool RSVGConvert --size 22 --theme Papirus`

**Comment by serovar** [comment]
Thanks varlesh, the issue was caused by my misunderstanding of the README, I thought that with the repo package, unlike the one built from source, the -E option was not necessary.

**Comment by bilelmoussaoui** [comment]
The -E option passes the env of the user to the root user. You always need that otherwise we can't detect your current icon theme or the scaling factor.
