### ISSUE TITLE
[Icon request] Barrier icon

### ISSUE THREAD

**Issue by atlas-ark** [bilelmoussaoui/Hardcode-Tray#604]
Hi,
Barrier (https://github.com/debauchee/barrier) icon is not supported yet. I'm using the latest version of hardcode-tray and the Papirus icon set on KDE Plasma 5.

**Comment by varlesh** [comment]
impossible. Icon on binary:
https://github.com/TafThorne/barrier/blob/master/src/gui/src/MainWindow.cpp#L292
https://github.com/TafThorne/barrier/blob/master/src/gui/src/MainWindow.cpp#L68
