### ISSUE TITLE
Qbittorrent

### ISSUE THREAD

**Issue by carmenfdezb** [bilelmoussaoui/Hardcode-Tray#607]
### Specifications
- Hardcode-Tray version : 4.3
- Distribution : Fedora 31 KDE
- Gtk version : 3.24
- Inkscape version : 0.92.4
- Cairo version : 1.16.0
- Sni-qt version: 0.2.7
- Application name :  Qbittorrent
- Application version : 4.1.7

### It doesn't work
![Screenshot_20191116_124206](https://user-images.githubusercontent.com/6286776/68992662-9526e380-086e-11ea-8dca-7ed31570f547.png)

### Steps to reproduce the problem
1. I run hardcode-tray (sudo hardcode-tray --theme Papirus-Dark)
2. Select 1 (Apply)
3. Qbittorrent is not detected by hardcode-tray

**Comment by varlesh** [comment]
qBittorrent not hardcoded and use icons for tray `qbittorrent` and `qbittorrent-tray` from plasma theme (if available) or from icon theme:
https://github.com/qbittorrent/qBittorrent/blob/master/src/gui/mainwindow.cpp#L150
https://github.com/qbittorrent/qBittorrent/blob/master/src/gui/mainwindow.cpp#L1967
![image](https://user-images.githubusercontent.com/8083855/68996326-de4c5700-08b1-11ea-9b8e-7aeb45ddf07a.png)
I fix it now on Materia KDE:

**Comment by carmenfdezb** [comment]
Thank you!
