### ISSUE TITLE
cant find lib32-sni-qt-patched-git in yay

### ISSUE THREAD

**Issue by ArchFeh** [bilelmoussaoui/Hardcode-Tray#610]
Error: Could not find all required packages:
    lib32-libmng (Wanted by: lib32-sni-qt-patched-git -> lib32-libdbusmenu-qt -> lib32-qt4)
Does it matter if no lib32-sni-qt-patched-git?

**Comment by varlesh** [comment]
sni-qt not needed anymore. Qt4-apps discontinued, but Qt5-apps not supported
