### ISSUE TITLE
I have installed numix theme but it says "Theme Numix Light does not exists."

### ISSUE THREAD

**Issue by arun54321** [bilelmoussaoui/Hardcode-Tray#614]
### Specifications
- Hardcode-Tray version : `4.3`
- Distribution : `Arch`
- Gtk version : `3.24`
- Inkscape version : `0.92`
- Application name :  `telegram`
- D.E : `KDE`

### Expected behavior and actual behavior
 It should patch
### Steps to reproduce the problem
1. sudo -E hardcode-tray  --only telegram --dark-theme "Numix Light" --light-theme "Numix"   

![image](https://user-images.githubusercontent.com/42943340/73048162-339e7900-3e9e-11ea-99c0-c50b29b35079.png)

**Comment by varlesh** [comment]
maybe  `--dark-theme "Numix-Light"`?

**Comment by arun54321** [comment]
> maybe `--dark-theme "Numix-Light"`?

Thanks. It now works.
