### ISSUE TITLE
Telegram-desktop 1.9.12 custom icon no longer working

### ISSUE THREAD

**Issue by AtomToast** [bilelmoussaoui/Hardcode-Tray#617]
### Specifications
- Hardcode-Tray version : `4.3`
- Distribution : `Arch Linux`
- Gtk version : `3.24
- Cairo version : `2.4.2` 
- Sni-qt version: `r.-1` (sni-qt-patched-git) 
- Application name :  `telegram-desktop`
- Application version : `1.9.12`

Since the newest update to telegram desktop the custom icon does not work anymore.  
For reference look here https://github.com/telegramdesktop/tdesktop/issues/7192

**Comment by HarDX** [comment]
Same, not working on 1.9.13 too

**Comment by varlesh** [comment]
i know. This broken with this PR:
https://github.com/telegramdesktop/tdesktop/pull/7111

**Comment by ilya-fedin** [comment]
It was a completely undocumented feature...

**Comment by AndydeCleyre** [comment]
Duplicate of #7192?

**Comment by varlesh** [comment]
update Telegram to 1.9.14 version. Now used tray icons with KDE Color Scheme support. But with right work need start app with this key (you can fix that on desktop file):
`env TDESKTOP_DISABLE_TRAY_COUNTER=1 Telegram`

**Comment by varlesh** [comment]
Telegram removed from database, because not needed anymore

**Comment by ilya-fedin** [comment]
> But with right work need start app with this key (you can fix that on desktop file)

there's a better way: you can add this variable to ~/.pam_environment or /etc/environment

**Comment by AtomToast** [comment]
Hm, this does not seem to work for me for some reason. The read notification marker stays on top.  
Also I noticed that I now have to start telegram with "telegram-desktop-bin" instead of just "telegram-desktop". Otherwise the icon won't work. Not sure what that's about

**Comment by varlesh** [comment]
> "telegram-desktop-bin" instead of just "telegram-desktop"

it does not matter. I think AUR maintainer rename binary file.

I don't know why this not worked for you... You try add `export TDESKTOP_DISABLE_TRAY_COUNTER=1` to `/etc/environment` or `~/.pam_environment` or `~/.profile`?

PS: Also with testing on GNOME that not good worked if you run Telegram from Terminal with that option... this worked only if option added to environment or desktop launcher (and run from launcher). For example:
`Exec=env TDESKTOP_DISABLE_TRAY_COUNTER=1 telegram-desktop -- %u`

**Comment by ilya-fedin** [comment]
btw, in 1.9.15 it should work for XEmbed trays too

**Comment by AtomToast** [comment]
I tried all of the options. The internal settings for displaying notification counts is also ignored.  

I am running a tiling window manager in DWM I only ever start it through the terminal. I don't have a launcher

**Comment by ilya-fedin** [comment]
> `export TDESKTOP_DISABLE_TRAY_COUNTER=1` to `/etc/environment` or `~/.pam_environment`

`export` won't work with /etc/environment or ~/.pam_environment, since they are read by pam rather than by shell, which doesn't know anything about `export`
They support only `KEY=VALUE` format.

**Comment by AtomToast** [comment]
After the most recent update to 1.9.21 it now all seems to work. The
environmental variable is still required. I personally have it set in my
~/.profile

**Comment by bicodegas** [comment]
Sorry, but what's environmental variable needed to make this work? I've tried everything you told and nothing seems to work.

**Comment by ilya-fedin** [comment]
> I'm using telegram 2.0.1 and Xfce if that's relevant.

If you're using telegram from static binary **and** Xfce's default tray applet, it is impossible to use system icon with telegram.

**Comment by bicodegas** [comment]
oh ok, you're right was using the static binary. If I use my distro's package it all works fine.
Thank you.
Cheers
