### ISSUE TITLE
Icons for applications located in /opt

### ISSUE THREAD

**Issue by BlueManCZ** [bilelmoussaoui/Hardcode-Tray#619]
### Specifications
- Hardcode-Tray version : `4.3`
- Distribution : `Gentoo Linux`
- Gtk version : `3.24`
- Inkscape version : `0.92.4`
- Application name :  `Mailspring`
- Application version : `1.7.2`

### Expected behavior and actual behavior
I'm trying to find default icons in mailspring directory according to [this database file](https://github.com/bilelmoussaoui/Hardcode-Tray/blob/4d6f72c4ade768e4a5fd134dd0e6460e60d14b29/data/database/mailspring.json), but all I get is `mailspring/resources/` directory:

`tree resources -L 1`
> resources
> ├── app.asar
> ├── app.asar.unpacked
> └── electron.asar

There is nothing like `internal_packages/system-tray/assets/linux/` in there.

I'm trying to run this command:
`sudo -E hardcode-tray --conversion-tool RSVGConvert --size 22 --theme Papirus --only mailspring --path /opt/mailspring-bin-1.7.2/resources`

But it returns: `No apps to fix!`

Am I doing something wrong, or is Mailspring support currently broken?

**Comment by varlesh** [comment]
> There is nothing `like internal_packages/system-tray/assets/linux/` in there.

This path packed on app.asar:
`/opt/mailspring-bin-1.7.2/resources/app.asar/internal_packages/system-tray/assets/linux/`

I think it's not worked, because script can not support `--path` with packed asar module.
Temporary solution - create symlink:
`sudo ln -s /opt/mailspring-bin-1.7.2 /usr/share/mailspring`
and fix icon:
`sudo -E hardcode-tray --conversion-tool RSVGConvert --size 22 --theme Papirus --only mailspring`

But it's not good way, because after update to next release symlink will be broken.

**Comment by varlesh** [comment]
after every update need fix icon, but in your case, you need remap symlink too:
`sudo ln -s /opt/mailspring-bin-1.7.3 /usr/share/mailspring`
`sudo ln -s /opt/mailspring-bin-1.7.4 /usr/share/mailspring`
and etc...
I think better solution for that write ebuild maintainer for remove release number from path

**Comment by BlueManCZ** [comment]
Thank you! Symlink did the trick. And I know that with ebuild it would be easier, but I haven't explored the creation of ebuilds much, maybe in the future.

**Comment by BlueManCZ** [comment]
But for example, I have Slack installed from [official repository](https://packages.gentoo.org/packages/net-im/slack-bin), and its default location is:

> \> ls /usr/bin/slack -l
> lrwxrwxrwx 1 root root 21 22. říj 14.27 /usr/bin/slack -> ../../opt/slack/slack

also `/opt` folder. So I guess, wouldn't be better implement something like $PATH environmental variable princip, which could contain multiple directories like: `/usr/share:/opt` and so on, and instead of putting absolute paths into [json database files](https://github.com/bilelmoussaoui/Hardcode-Tray/blob/4d6f72c4ade768e4a5fd134dd0e6460e60d14b29/data/database/slack.json), use only relative and look for them in specified directories?

**Comment by BlueManCZ** [comment]
And when I mentioned Slack, in [slack.json](https://github.com/bilelmoussaoui/Hardcode-Tray/blob/4d6f72c4ade768e4a5fd134dd0e6460e60d14b29/data/database/slack.json) there is path `slack/resources/app.asar.unpacked/static/` and in there icons as `.png` files. But in my system I found only `slack/resources/app.asar.unpacked/dist/static` and icons as `.ico` files.

![Snímek z 2020-02-25 11-23-14](https://user-images.githubusercontent.com/17854950/75238404-3bb14780-57c1-11ea-91fa-bffe267de3fa.png)

**Comment by varlesh** [comment]
> also /opt folder. So I guess, wouldn't be better implement something like $PATH environmental variable princip, which could contain multiple directories like: /usr/share:/opt and so on, and instead of putting absolute paths into json database files, use only relative and look for them in specified directories?

Usualy we set path from AUR & DEB packages.
If ebuild maintainer change path for mailspring, we can add this path to database. For example:
```
"app_path": [
        "/usr/share/mailspring/",
        "/opt/mailspring-bin"
    ],
    "icons_path": [
        "/usr/share/mailspring/resources/",
        "/opt/mailspring-bin/resources/"
    ],
```

> Or does Slack still use base64 icons?

Yes, Slack use Base64 icons and hardcode-tray not support that now.

PS: I'm not developer on this repo and don't know python ((

**Comment by JoeJoeTV** [comment]
Hello, i also have installed some applications in `/opt`, like Telegram, because there is only a .tar.gz version, so I made a new folder in `/opt` and put it there. Also whatsapp-desktop application is installed from the repository/software manager.
Both of these still have their normal colored icons, but the whatsapp-desktop one is the one from my theme, but not the white tray version.

**Comment by BlueManCZ** [comment]
@JoeJoeTV Please check [this file](https://github.com/bilelmoussaoui/Hardcode-Tray/blob/master/data/database/whatsapp.json) and make a sure path where you placed your Whatsapp matches one of mentioned in the file. It's case-sensitive.

**Comment by JoeJoeTV** [comment]
@BlueManCZ I installed whatsapp from then repository, so it installed itself in `/opt/whatsapp-desktop/` and there are the right icons in `/opt/whatsapp-desktop/resources/app/assets/icon`, but hardcode-tray doesn't use those?
![image](https://user-images.githubusercontent.com/34209417/81154598-5a337c00-8f84-11ea-9d46-ad3fd84c5b88.png)

**Comment by BlueManCZ** [comment]
@JoeJoeTV Well, this is probably not a problem of hardcode-tray, because icons are replaced correctly, but the problem of WhatsApp, that it doesn't use those icons. I don't know about Telegram, but maybe it has the same problem, so it's no longer supported.

**Comment by JoeJoeTV** [comment]
I looked over the code for a bit and saw, that whatsapp-desktop should be using the icons in the assets/icons directory, but somehow doesn't?
I also tried reverting hardcode-tray, but there were only snapshots from today?

**Comment by BlueManCZ** [comment]
I'm afraid I can't help you. I'm out of ideas, I've never been even using Whatsapp. You can create a new issue if nobody response here.

**Comment by varlesh** [comment]
Telegram already use system icons for tray with environment options on `~/.profile`
KDE:
`export TDESKTOP_DISABLE_TRAY_COUNTER=1`
Gnome:
```
export TDESKTOP_FORCE_PANEL_ICON=1
export TDESKTOP_DISABLE_TRAY_COUNTER=1
```
more info [here](https://github.com/telegramdesktop/tdesktop/wiki/Environment-variables) 

About Whatsapp Desktop - version 0.6.1 from Mint [repo](http://packages.linuxmint.com/pool/import/w/whatsapp-desktop/) - worked
![image](https://user-images.githubusercontent.com/8083855/81168671-7a753200-8fa8-11ea-9376-35d66aec28c1.png)

**Comment by JoeJoeTV** [comment]
@varlesh I'm gonna try the env variables, although, telegram started doing it by itself after the last update.
I'm on Mint 19.3 Cinnamon, so I already have v0.6.1 from the mint repo.
Is there a way to revert the changes from hardcode-tray, because the command line option doesn't work and only allows me to reset to today morning. Can I reset the icons manually, does hardcode-tray change the theme files?

**Comment by varlesh** [comment]
reinstall package

**Comment by BlueManCZ** [comment]
@varlesh I tested that environmental variables, but It seems to have no effect at all in my Telegram 2.1.1. Strange.

**Comment by varlesh** [comment]
@BlueManCZ you reboot PC?

**Comment by BlueManCZ** [comment]
@varlesh Why would I do that? With environmental variables this should be enough:
```
killall telegram-desktop
export TDESKTOP_FORCE_PANEL_ICON=1
export TDESKTOP_DISABLE_TRAY_COUNTER=1
telegram-desktop
```

But it seems it isn't.
![Snímek z 2020-05-06 13-57-27](https://user-images.githubusercontent.com/17854950/81174168-9fb27200-8fa1-11ea-82ce-20d54c98874a.png)

**Comment by varlesh** [comment]
Yes, if you start this as script

**Comment by varlesh** [comment]
![image](https://user-images.githubusercontent.com/8083855/81175631-e6f62e00-8fb4-11ea-9fdd-a00a877300ba.png)

**Comment by varlesh** [comment]
@BlueManCZ On your screenshot not Papirus icon theme

**Comment by BlueManCZ** [comment]
@varlesh You are right, that was it. No Papirus icon theme.

![Snímek z 2020-05-06 14-22-54](https://user-images.githubusercontent.com/17854950/81176201-1a30c100-8fa5-11ea-953c-7ea802f1dd68.png)

**Comment by nicolasmaia** [comment]
> Yes, if you start this as script

How?

**Comment by BlueManCZ** [comment]
@nicolasmaia He means you don't need to restart, if you run mentioned commands together.

**Comment by varlesh** [comment]
```
echo "export TDESKTOP_FORCE_PANEL_ICON=1" >> ~/.profile
echo "export TDESKTOP_DISABLE_TRAY_COUNTER=1" >> ~/.profile
reboot
```

**Comment by nicolasmaia** [comment]
> ```
> echo "export TDESKTOP_FORCE_PANEL_ICON=1" >> ~/.profile
> echo "export TDESKTOP_DISABLE_TRAY_COUNTER=1" >> ~/.profile
> reboot
> ```

Thanks. I just tried this, to no avail.

**Comment by varlesh** [comment]
@nicolasmaia It's worked if this icons for tray available on current icon theme:
```
telegram-attention-panel
telegram-mute-panel
telegram-panel
```

**Comment by varlesh** [comment]
@nicolasmaia What you use DE & Icon Theme?

**Comment by varlesh** [comment]
Also i don't know how this worked with snap & flatpak. It's tested with only Telegram binary version from githab releases

**Comment by nicolasmaia** [comment]
Gnome Shell 3.30.2, Icon theme is ZorinBlue-Light.

**Comment by BlueManCZ** [comment]
@nicolasmaia Yea, that's the problem. I guess Zorin theme doesn't have Telegrams tray icons. Switch to [Papirus](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme) icon theme and try it again. I also created [this question](https://unix.stackexchange.com/questions/584962/force-application-to-use-specific-icon-theme) to see, if there are any possibilities to force Telegram to use specific icon pack. Another way would be to create symlinks to Papirus icons in your selected icon theme.

**Comment by BlueManCZ** [comment]
Solution with symlinks did the trick for me.

**Comment by nicolasmaia** [comment]
Can you share how you did it with symlinks?

**Comment by BlueManCZ** [comment]
You need to have a Papirus theme installed.
I will demonstrate it with Numix-Circle theme, but you should adapt it for yours.

```
# enter a folder of your icon theme
cd /usr/share/icons/Numix-Circle/16/panel

# and create three symlinks
sudo ln -s /usr/share/icons/Papirus/16x16/panel/telegram-attention-panel.svg telegram-attention-panel.svg
sudo ln -s /usr/share/icons/Papirus/16x16/panel/telegram-mute-panel.svg telegram-mute-panel.svg 
sudo ln -s /usr/share/icons/Papirus/16x16/panel/telegram-panel.svg telegram-panel.svg
```

That's all what I did.

**Comment by mateushonorato** [comment]
> ```
> echo "export TDESKTOP_FORCE_PANEL_ICON=1" >> ~/.profile
> echo "export TDESKTOP_DISABLE_TRAY_COUNTER=1" >> ~/.profile
> reboot
> ```

this was working fine but on latest updates telegram seems to have changed something and now it doesn't work anymore

**Comment by varlesh** [comment]
This env droped. More info here:
https://github.com/telegramdesktop/tdesktop/pull/9056
