### ISSUE TITLE
Electron apps like Bitwarden and Android Messages Desktop not detected

### ISSUE THREAD

**Issue by yochananmarqos** [bilelmoussaoui/Hardcode-Tray#620]
### Specifications
- Hardcode-Tray version : `4.3.r76.g7f253b8` 
- Distribution : `Manjaro`
- Gtk version : `3.24.14`
- Cairo version : `2.4.2`

### Expected behavior and actual behavior

I'm using the `bitwarden` and `android-messages-desktop` packages from the AUR. When I choose to apply, neither application are listed. Nothing appears in the log mentioning either application. Both store their icons in `/usr/share/icons/`, so perhaps that path could be added as well as inside the `app.asar`.

```
$ sudo hardcode-tray
Welcome to Hardcode-Tray!
Hardcode-Tray replaces some icons on the binary files of some applications. 
Please close all the running applications before running Hardcode-Tray script.
Desktop Environment: Other
Scaling Factor: 1
Icon Size: 22
Icon Theme: Papirus-Dark-Maia
Conversion Tool: CairoSVG
To Do: All
1 - Apply
2 - Revert
3 - Clear Backup Cache
Please choose: 1
Applying now..


Chromium            [####................................] 1/9 11.1% 0.02s
Google Chrome       [########............................] 2/9 22.2% 0.02s
HP Printer          [############........................] 3/9 33.3% 0.00s
JDownloader         [################....................] 4/9 44.4% 0.00s
Keybase             [####################................] 5/9 55.6% 0.01s
MullvadVPN          [########################............] 6/9 66.7% 0.09s
Solaar              [############################........] 7/9 77.8% 0.01s
Steam               [################################....] 8/9 88.9% 0.00s
Vivaldi             [####################################] 9/9 100.0% 0.01s
Took 0.17s to finish the tasks

Done, Thank you for using the Hardcode-Tray fixer!
```

**Comment by varlesh** [comment]
Usualy some electron apps located on another directory
Also sometime compiled apps may be have unpacked asar resources.

i think asar bitwarden located here `/usr/lib/bitwarden/resources/`... [link](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=bitwarden#n66)

But why not applied android-messages-desktop it's strange, because this path `/usr/lib/android-messages-desktop` [already exist](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=android-messages-desktop#n26)

You can find icon name `icon.png` and `app.asar` on directories  `/usr/lib/android-messages-desktop` and `/usr/lib/bitwarden`?

**Comment by yochananmarqos** [comment]
FYI, I just updated the `android-messages-desktop` package to build from source and created a new binary package, `android-messages-desktop-bin`.

The `icon.png` does not exist as the `app.asar` is not unpacked.

```
/usr/lib/android-messages-desktop/
└── resources
    ├── app.asar
    └── resources
        └── dictionaries
```

```
/usr/lib/bitwarden/
└── resources
    └── app.asar
```

**Comment by varlesh** [comment]
if app.asar not unpacked - tray icon used from app.asar...
But it's strange for android-messages-desktop

**Comment by varlesh** [comment]
i'm added path to bitwarden, but not understand why not worked android-messages-desktop

**Comment by varlesh** [comment]
DEB version:
![image](https://user-images.githubusercontent.com/8083855/75704497-eac6b500-5cd2-11ea-986f-0bf14f7cd8a0.png)

**Comment by yochananmarqos** [comment]
Aha! With that commit and me fixing the `app.asar` path in `android-messages-desktop`, it works for both now. Thanks!
