### ISSUE TITLE
[Icon request] Zoom

### ISSUE THREAD

**Issue by kuriot** [bilelmoussaoui/Hardcode-Tray#621]
Hi. As Zoom become used more often it would be nice to fix its icon too.

Application name: Zoom
Icon name: Zoom

How it looks now:

![Screenshot_20200303_142639](https://user-images.githubusercontent.com/25008488/75771440-0d041580-5d5b-11ea-84c9-461de54af724.png)

Thanks!

**Comment by varlesh** [comment]
impossible. Qt5 apps not supported. Icon used from binary
