### ISSUE TITLE
Feature Request: Add support for Keybase application

### ISSUE THREAD

**Issue by spielkind** [bilelmoussaoui/Hardcode-Tray#623]
Please add support for new Keybase icons.
Filelist here:
https://www.archlinux.org/packages/community/x86_64/keybase-gui/

Thanks.

**Comment by varlesh** [comment]
updated:
https://github.com/bilelmoussaoui/Hardcode-Tray/commit/dac49a683efd41538fcb04eecca2f157f3557223
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/commit/08600b3eb88aad3b401829fd4051a0d6b2772f75
