### ISSUE TITLE
Tartube support

### ISSUE THREAD

**Issue by HarDX** [bilelmoussaoui/Hardcode-Tray#624]
Can you support Tartube
https://github.com/axcore/tartube

**Comment by varlesh** [comment]
You can show screenshot what icons used on tray?

**Comment by varlesh** [comment]
https://github.com/axcore/tartube/blob/master/tartube/formats.py#L571

**Comment by HarDX** [comment]
![Screenshot_20200317_125206](https://user-images.githubusercontent.com/5231223/76834157-79e4d880-684e-11ea-9dd0-3a6bbb91b605.png)

**Comment by varlesh** [comment]
![image](https://user-images.githubusercontent.com/8083855/76835539-b6153a80-6848-11ea-9ee8-88e4a8ae74a6.png)
application used xmas icons... i think it's not needed for hack

**Comment by HarDX** [comment]
thanks, i try change it

**Comment by varlesh** [comment]
added
![image](https://user-images.githubusercontent.com/8083855/76840369-80744f80-6850-11ea-9dfb-08ac9a9b0c69.png)
