### ISSUE TITLE
It doesn't work when I use other icon themes

### ISSUE THREAD

**Issue by carmenfdezb** [bilelmoussaoui/Hardcode-Tray#625]
### Specifications
- Hardcode-Tray version : `4.3`
- Distribution : `Fedora 31 KDE`
- Gtk version : `3.24`
- Inkscape version : `1.0beta2`

### Description
I'm using Uniform+ icons theme, but icons tray don't change when I apply harcode-tray with Papyrus-Dark icons.
![Screenshot_20200328_155710](https://user-images.githubusercontent.com/6286776/77825966-e09aa980-710c-11ea-91e2-e677ad76c5ce.png)

For me it only works when I use Papyrus or Numix icon themes.

### Steps to reproduce the problem
1. sudo -E hardcode-tray --conversion-tool RSVGConvert --size 22 --theme Papirus-Dark
2. tray icons don't change (telegram and dropbox)

**Comment by varlesh** [comment]
Telegram & Dropbox not hardcoded. Used tray icons from system icon theme:
```
telegram-panel
telegram-mute-panel
telegram-attention-panel
```

```
dropboxstatus-x
dropboxstatus-busy
dropboxstatus-idle
dropboxstatus-logo
dropboxstatus-blank
dropboxstatus-busy2
```
also for telegram info here:
https://github.com/telegramdesktop/tdesktop/issues/7192
