### ISSUE TITLE
Hardcode-Tray does not detect Chromium

### ISSUE THREAD

**Issue by serovar** [bilelmoussaoui/Hardcode-Tray#626]
### Specifications
- Hardcode-Tray version : `4.3`
- Distribution : `Fedora 31`
- Gtk version : `4.3`
- Cairo version : `1.16.0`
- Application name :  `Chromium`
- Application version : `80.0.3987.149`

### Expected behavior and actual behavior
Hardcode-Tray should list Chromium among the applications of which it can change the tray icon, and change it. It actually does not list it and does not change it.

This is the output I get:
```
sudo -E hardcode-tray --apply
Welcome to Hardcode-Tray!
Hardcode-Tray replaces some icons on the binary files of some applications. 
Please close all the running applications before running Hardcode-Tray script.
Desktop Environment: Xfce
Scaling Factor: 1
Icon Size: 24
Icon Theme: Papirus-Dark
Conversion Tool: CairoSVG
To Do: All
Applying now..


Dropbox             [###.................................] 1/11 9.1% 0.01s
Google Chrome       [#######.............................] 2/11 18.2% 0.02s
Hexchat             [##########..........................] 3/11 27.3% 0.00s
Insync              [#############.......................] 4/11 36.4% 0.01s
Keybase             [################....................] 5/11 45.5% 0.01s
Megasync            [####################................] 6/11 54.5% 0.00s
MullvadVPN          [#######################.............] 7/11 63.6% 0.08s
Rambox              [##########################..........] 8/11 72.7% 0.65s
Skype               [#############################.......] 9/11 81.8% 3.36s
Steam               [#################################...] 10/11 90.9% 0.00s
Microsoft Teams     [####################################] 11/11 100.0% 0.00s
Took 4.13s to finish the tasks

Done, Thank you for using the Hardcode-Tray fixer!
```
Of note, it does detect Google Chrome, but it does not change its tray icon (I will open another issue for it, if it is not correlated).

The other applications have their tray icon modified just fine.

### Steps to reproduce the problem
1. `sudo -E hardcode-tray --apply` with Chromium installed

**Comment by varlesh** [comment]
updated version for Chrome/Chromium 80 & added path for Fedora:
https://github.com/bilelmoussaoui/Hardcode-Tray/commit/0108133a7b987268159584ab362b3b27287765f4
https://github.com/bilelmoussaoui/Hardcode-Tray/commit/3d1f67d4fdb1ab0ea136d4a93112215805a08884

**Comment by rauldipeas** [comment]
I think that's Chromium needs to be updated again.
![Screenshot_5](https://user-images.githubusercontent.com/12108031/190872487-01291b4c-32fc-4b36-bf62-667020a4f1cb.png)

**Comment by varlesh** [comment]
updated

**Comment by rauldipeas** [comment]
Thank You so much!

**Comment by rauldipeas** [comment]
It's not working again... 😞 
![Screenshot_14](https://user-images.githubusercontent.com/12108031/192878691-20a7fc25-6f1d-4418-b336-cec027cdc8ad.png)

**Comment by varlesh** [comment]
updated
