### ISSUE TITLE
Mullvad VPN tray icon no longer changed

### ISSUE THREAD

**Issue by serovar** [bilelmoussaoui/Hardcode-Tray#627]
### Specifications
- Hardcode-Tray version : `4.3`
- Distribution : `Fedora 31`
- Gtk version : `3.24`
- Cairo version : `1.16.0`
- Application name :  `Mullvad VPN`
- Application version : `2020.3`

### Expected behavior and actual behavior
hardcode-tray should detect it and change its tray icon.
It does detect it, but it does not change it.
### Steps to reproduce the problem
1. Install the Mullvad VPN app
2. `sudo -E hardcode-tray --apply`
3. Start the app

In previous versions of the Mullvad app it worked perfectly fine, but in recent ones something changed (maybe they changed the name of the tray icon when they added the monochrome version one?).

**Comment by varlesh** [comment]
updated. Tested with DEB 2020.3
