### ISSUE TITLE
Can't install on Fedora 32

### ISSUE THREAD

**Issue by serovar** [bilelmoussaoui/Hardcode-Tray#628]
### Specifications
- Distribution : `Fedora 32`

### Issue
hardcode-tray cannot be installed on Fedora 32 (and it blocks the system upgrade if coming from Fedora 31).

```
Error: 
 Problem: conflicting requests
 - nothing provides python(abi) = 3.7 needed by hardcode-tray-4.3.r90.gf3e2d59-40.1.noarch
```

**Comment by varlesh** [comment]
@SmartFinn

**Comment by SmartFinn** [comment]
Nothing weird here, because OBS provide separated repo per each distro version. You have to remove a package and the repo for Fedora 31 before upgrade:

```sh
sudo dnf remove hardcode-tray
sudo rm /etc/yum.repos.d/home:SmartFinn:hardcode-tray.repo
```

And then install it for Fedora 32:

```sh
sudo dnf config-manager --add-repo https://download.opensuse.org/repositories/home:SmartFinn:hardcode-tray/Fedora_$(rpm -E %fedora)/home:SmartFinn:hardcode-tray.repo
sudo dnf install hardcode-tray
```
