### ISSUE TITLE
Telegram not being detected

### ISSUE THREAD

**Issue by nicolasmaia** [bilelmoussaoui/Hardcode-Tray#629]
### Specifications
- Hardcode-Tray version : `4.3`
- Distribution : `Zorin OS 15.2`
- Gtk version : `3.22`
- Inkscape version : `` if installed
- Cairo version : `` if installed
- Sni-qt version: `` if installed
- Application name :  `telegram-desktop`
- Application version : `2.1`

### Expected behavior and actual behavior
Upon running `sudo -E hardcode-tray --apply`, it detects and correctly fixes the icon for Steam, but it doesn't detect Telegram at all.

To be clear, this is not a snap package, it was installed through apt from the ppa:mymedia/telegram repository. I also tried installing the outdated version from the ubuntu bionic repos (Zorin is based on this release), and the same problem happens.

### Steps to reproduce the problem
1. Run `sudo -E hardcode-tray --apply`
2. Watch as telegram-desktop is undetected

**Comment by varlesh** [comment]
https://github.com/bilelmoussaoui/Hardcode-Tray/issues/619#issuecomment-624576646
