### ISSUE TITLE
X Tile

### ISSUE THREAD

**Issue by rauldipeas** [bilelmoussaoui/Hardcode-Tray#632]
> for tray used `/usr/share/x-tile/glade/tile-quad.svg` This can be fixed on hardcode-tray, but this icon use on interface

_Originally posted by @varlesh in https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/2187#issuecomment-627714740_

**Comment by rauldipeas** [comment]
I think that's something wrong...
![image](https://user-images.githubusercontent.com/12108031/81886273-a2e5c900-9572-11ea-9d07-9a60df7d0d44.png)

**Comment by varlesh** [comment]
try convert with another size

**Comment by rauldipeas** [comment]
All sizes are getting a ugly icon.
This is 16px, with 22px and 24px it's the same of last screenshot.
![image](https://user-images.githubusercontent.com/12108031/81886716-c78e7080-9573-11ea-85a9-6311f52f5a6d.png)

**Comment by varlesh** [comment]
you don't like style?

**Comment by rauldipeas** [comment]
> you don't like style?

The original one it's much better.

I think it's should be more white, without X.

**Comment by varlesh** [comment]
ok

**Comment by varlesh** [comment]
updated, without X

**Comment by rauldipeas** [comment]
> updated, without X

Thank you, waiting for PPA to update.

**Comment by varlesh** [comment]
you can update without PPA, use Papirus Installer

**Comment by rauldipeas** [comment]
Really, thanks for the tip.

But i'm still getting the same problem with size, too small.
This is 16px.
![image](https://user-images.githubusercontent.com/12108031/81888409-a7f94700-9577-11ea-81ba-350cdc649d93.png)

**Comment by varlesh** [comment]
on KDE it's looking even worse. All sizes blurred

**Comment by rauldipeas** [comment]
Any chance to enhance this icon?
