### ISSUE TITLE
JDownloader 2 Tray Icon Not Applied on Manjaro KDE Plasma 5.18.5

### ISSUE THREAD

**Issue by LazyGeniusMan** [bilelmoussaoui/Hardcode-Tray#634]
### Specifications
- Hardcode-Tray version : `4.3` and `git` from AUR (tried both)
- Distribution : `Manjaro KDE 20.0.1`
- Gtk version : `latest` (?) , from manjaro repo `gtk2` and `gtk3` is installed and up to date.
- Inkscape version : `1.0-3`
- Cairo version : `1.17.2`
- Sni-qt version: Not Installed
- Application name :  `JDownloader2`
- Application version : `latest` from AUR

### Expected behavior and actual behavior
Expected : JDownloader tray icon not hardcoded
Actual : Jdownloader tray icon still hardcoded

### Steps to reproduce the problem
1.  Install `papirus-icon-theme` & Apply
2. Install `Hardcode-Tray`
3. run `sudo -E hardcode-tray --conversion-tool RSVGConvert --size 22 --theme Papirus` and then press 1
4. Reboot

```
** (hardcode-tray:4024): WARNING **: 07:43:33.614: Unable to connect to dbus: The connection is closed
Welcome to Hardcode-Tray!
Hardcode-Tray replaces some icons on the binary files of some applications. 
Please close all the running applications before running Hardcode-Tray script.
Desktop Environment: Kde
Scaling Factor: 1
Icon Size: 22
Icon Theme: Papirus
Conversion Tool: RSVGConvert
To Do: All
1 - Apply
2 - Revert
3 - Clear Backup Cache
Please choose: 1
Applying now..


Discord             [#########...........................] 1/4 25.0% 0.09s
HP Printer          [##################..................] 2/4 50.0% 0.00s
JDownloader         [###########################.........] 3/4 75.0% 0.01s
Steam               [####################################] 4/4 100.0% 0.02s
Took 0.12s to finish the tasks

Done, Thank you for using the Hardcode-Tray fixer!

```
I've tried with `--theme Papirus-Dark` too.

**Comment by varlesh** [comment]
This app written on java and render bugged tray icons:
transparent:
![image](https://user-images.githubusercontent.com/8083855/82133971-1998f580-9803-11ea-817b-d46655dafec8.png)

non-transparent (with background):
![image](https://user-images.githubusercontent.com/8083855/82133943-c0c95d00-9802-11ea-998e-b8495c8ef53e.png)

**Comment by varlesh** [comment]
database updated https://github.com/bilelmoussaoui/Hardcode-Tray/commit/1f20ed7dd4b43d50ea5bba69391475fd7e69f8a4
but it's useless

**Comment by LazyGeniusMan** [comment]
> database updated [1f20ed7](https://github.com/bilelmoussaoui/Hardcode-Tray/commit/1f20ed7dd4b43d50ea5bba69391475fd7e69f8a4)
> but it's useless

@varlesh Are you sure it's `~/.jd2/...` instead of `~/.jd/...` ? I dont see `.jd2` folder on `~`
![image](https://user-images.githubusercontent.com/58850480/82134247-1e1fd700-9820-11ea-8ca1-9218ec3a1fea.png)

**Comment by varlesh** [comment]
added ~/.jd too

**Comment by LazyGeniusMan** [comment]
> added ~/.jd too [8b2dad9](https://github.com/bilelmoussaoui/Hardcode-Tray/commit/8b2dad9b0e0d26729ac354145a102b98aef10213)

@varlesh Mine got changed into solid square :/,  but the icon is changed according to .json path :/
![image](https://user-images.githubusercontent.com/58850480/82135865-cee2a200-9831-11ea-9221-07a3f2c57b46.png)

> non-transparent (with background):
> ![image](https://user-images.githubusercontent.com/8083855/82133943-c0c95d00-9802-11ea-998e-b8495c8ef53e.png)

how did you get this ?, what did you do?

**Comment by varlesh** [comment]
@LazyGeniusMan open on gimp and added background))

**Comment by LazyGeniusMan** [comment]
> @LazyGeniusMan open on gimp and added background))

@varlesh ah ok, it's looks good now. Thanks.
