### ISSUE TITLE
[Icon Request] ytmdesktop

### ISSUE THREAD

**Issue by yochananmarqos** [bilelmoussaoui/Hardcode-Tray#642]
### Specifications
- Hardcode-Tray version : `4.3`
- Distribution : `Manjaro GNOME`
- Gtk version : `3.24.20`
- Inkscape version : `1.0`
- Cairo version : `1.17.2`
- Application name :  `ytmdesktop`
- Application version : `1.11.0`

- [Upstream URL](https://github.com/ytmdesktop/ytmdesktop)
- VCS [AUR package](https://aur.archlinux.org/packages/ytmdesktop-git) using `/opt/ytmdesktop`
- My [AUR package](https://aur.archlinux.org/packages/ytmdesktop) using `/usr/lib/ytmdesktop`

**Comment by varlesh** [comment]
added, but not  tested... app contained also:

- favicon.16x16.png
- favicon.256x256.png
- favicon.512x512.png
But i think it's not used on tray

**Comment by yochananmarqos** [comment]
It's not detecting either package for some reason.

```
Welcome to Hardcode-Tray!
Hardcode-Tray replaces some icons on the binary files of some applications. 
Please close all the running applications before running Hardcode-Tray script.
Desktop Environment: Other
Scaling Factor: 1
Icon Size: 24
Icon Theme: Papirus-Dark-Maia
Conversion Tool: RSVGConvert
To Do: All
1 - Apply
2 - Revert
3 - Clear Backup Cache
Please choose: 1
Applying now..


Android Messages Desktop    [###.................................] 1/13 7.7% 0.15s
Bitwarden           [######..............................] 2/13 15.4% 0.09s
Chromium            [########............................] 3/13 23.1% 0.15s
Google Chrome       [###########.........................] 4/13 30.8% 0.15s
HP Printer          [##############......................] 5/13 38.5% 0.00s
JDownloader         [#################...................] 6/13 46.2% 0.02s
Keybase             [###################.................] 7/13 53.8% 0.38s
MullvadVPN          [######################..............] 8/13 61.5% 1.44s
Nicotine +          [#########################...........] 9/13 69.2% 0.08s
Skype               [############################........] 10/13 76.9% 3.15s
Solaar              [##############################......] 11/13 84.6% 0.12s
Steam               [#################################...] 12/13 92.3% 0.02s
Vivaldi             [####################################] 13/13 100.0% 0.05s
Took 5.80s to finish the tasks

Done, Thank you for using the Hardcode-Tray fixer!
```

**Comment by varlesh** [comment]
Papirus-Dark-Maia maybe not contained icons?
Try it with fresh git-version Papirus

**Comment by varlesh** [comment]
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/commit/67aab707707646a1d4d5699a87524970b7915603

**Comment by yochananmarqos** [comment]
[`papirus-maia-icon-theme`](https://gitlab.manjaro.org/artwork/icon-themes/papirus-maia-icon-theme) depends on `papirus-icon-theme`, so it should work as it has before. I installed `papirus-icon-theme-git` from the AUR, still no luck. I also tried `--theme Papirus-Dark`.

**Comment by varlesh** [comment]
i'm extract appimage 1.11 version and unpack app.asar. This file contained icons:

- app.asar/src/assets/favicon_pause.icns
- app.asar/src/assets/favicon_pause.ico
- app.asar/src/assets/favicon_pause.png
- app.asar/src/assets/favicon_play.icns
- app.asar/src/assets/favicon_play.ico
- app.asar/src/assets/favicon_play.png
- app.asar/src/assets/favicon.16x16.png
- app.asar/src/assets/favicon.256x256.png
- app.asar/src/assets/favicon.512x512.png
- app.asar/src/assets/favicon.icns
- app.asar/src/assets/favicon.ico
- app.asar/src/assets/favicon.png

Ico - Windows
Icns - OSX
png - Linux

Files path added to database and Papirus to

**Comment by varlesh** [comment]
![image](https://user-images.githubusercontent.com/8083855/85354565-eccfb080-b51b-11ea-9f3f-a3deeacb96f5.png)
```
{
    "name": "YouTube Music Desktop",
    "app_path": [
        "/opt/ytmdesktop/",
        "/usr/lib/ytmdesktop"
    ],
    "icons_path": [
        "/opt/ytmdesktop/resources/",
        "/usr/lib/ytmdesktop/resources/"
    ],
    "binary": "app.asar",
    "script": "electron",
    "icons": {
        "tray": {
            "original": "src/assets/favicon.png",
            "theme": "youtube-music-desktop-app-tray"
        },
        "tray-play": {
            "original": "src/assets/favicon_play.png",
            "theme": "youtube-music-desktop-app-tray-play"
        },
        "tray-pause": {
            "original": "src/assets/favicon_pause.png",
            "theme": "youtube-music-desktop-app-tray-pause"
        }
    }
}
```

**Comment by yochananmarqos** [comment]
As far as I've seen, the tray icon does not change when the player is paused. Not sure if that has anything to do with it or not.

**Comment by yochananmarqos** [comment]
Turns out it is applying:

```
YouTube Music Desktop [####################################] 14/14 100.0% 0.96s
```

However, the tray icon is still the original.

**Comment by varlesh** [comment]
My fault, sorry. This app use base64image, but this not supported:
https://github.com/ytmdesktop/ytmdesktop/blob/master/src/icons_for_shiny_tray.js
Similar problem with Slack:
https://github.com/bilelmoussaoui/Hardcode-Tray/issues/605

**Comment by varlesh** [comment]
for info: 
icons located on `app.asar/src/icons_for_shiny_tray.js`

**Comment by BlueManCZ** [comment]
I just tested this and it doesn't use base64. It looks like it uses the default system icon, because tray icon changes dynamically with icon themes without an application restart.

Papirus:
![Snímek z 2020-07-31 00-08-24](https://user-images.githubusercontent.com/17854950/88979490-18d01580-d2c2-11ea-8809-afe50451fdcf.png)
Numix:
![Snímek z 2020-07-31 00-08-49](https://user-images.githubusercontent.com/17854950/88979499-1d94c980-d2c2-11ea-8a1e-5c5dd178439f.png)

**Comment by varlesh** [comment]
@BlueManCZ But how draw pause & play state?
on KDE appimage draw this:
![image](https://user-images.githubusercontent.com/8083855/89000691-09c08600-d309-11ea-9eec-d14a1c0babd0.png)
![image](https://user-images.githubusercontent.com/8083855/89000638-e8f83080-d308-11ea-9ba9-64e10d69025e.png)
![image](https://user-images.githubusercontent.com/8083855/89000659-f6adb600-d308-11ea-86e3-ecbe069c7383.png)

**Comment by BlueManCZ** [comment]
@varlesh I didn't test it on KDE. On Gnome these icons never appeared. I will look into it and let you know.

**Comment by BlueManCZ** [comment]
You are right, on KDE it behaves differently. But I can only confirm it doesn't use base64. I found icons in `app.asar/src/assets`, I will give it a try.

![Snímek obrazovky pořízený 2020-07-31 12-18-49](https://user-images.githubusercontent.com/17854950/89025931-04beff00-d328-11ea-8ee2-404f8459c3b2.png)

**Comment by varlesh** [comment]
See my comment https://github.com/bilelmoussaoui/Hardcode-Tray/issues/642#issuecomment-647871023
I try only png's. How say @yochananmarqos this not worked

**Comment by varlesh** [comment]
If app superimposed `pause.png` & `play.png` on main icon -  it's impossible themable or very hard doing this.
Anyway this app strange draw tray icons

**Comment by BlueManCZ** [comment]
But keep in mind, @yochananmarqos tested it on Gnome, as I did before https://github.com/bilelmoussaoui/Hardcode-Tray/issues/642#issuecomment-666739813. It uses system-icons in Gnome.

**Comment by BlueManCZ** [comment]
@varlesh Your [.json](https://github.com/bilelmoussaoui/Hardcode-Tray/issues/642#issuecomment-647871023) file works on KDE for me.

![Snímek obrazovky pořízený 2020-07-31 12-55-55](https://user-images.githubusercontent.com/17854950/89028826-5c139e00-d32d-11ea-8454-d56547d1260d.png)
![Snímek obrazovky pořízený 2020-07-31 12-56-22](https://user-images.githubusercontent.com/17854950/89028834-603fbb80-d32d-11ea-83ba-d5b7021d04f6.png)
![Snímek obrazovky pořízený 2020-07-31 12-56-46](https://user-images.githubusercontent.com/17854950/89028841-62a21580-d32d-11ea-826e-595c8b5a9cbd.png)

**Comment by BlueManCZ** [comment]
Now the question is, how to fix this icon in Gnome? Are there any cases like this, where the icon behaves differently in Gnome than in KDE? @varlesh  @bilelmoussaoui

**Comment by varlesh** [comment]
It's good news)) I can't test it because have only appimage & DEB-based distro.
I think it's will be worked for GNOME with KDE environment hack:
`XDG_CURRENT_DESKTOP=KDE ytmdesktop`
Try it

**Comment by BlueManCZ** [comment]
You are right!

With `XDG_CURRENT_DESKTOP=GNOME`:

![Snímek z 2020-07-31 13-05-59](https://user-images.githubusercontent.com/17854950/89029422-b7925b80-d32e-11ea-837d-107c460ea2c3.png)

With `XDG_CURRENT_DESKTOP=KDE`:

![Snímek z 2020-07-31 13-06-19](https://user-images.githubusercontent.com/17854950/89029474-d395fd00-d32e-11ea-8e2c-6230258c8f6e.png)

**Comment by varlesh** [comment]
Ok. Closed

**Comment by varlesh** [comment]
@yochananmarqos As solution use KDE env option.
Change Exec on desktop file to:
`Exec=XDG_CURRENT_DESKTOP=KDE ytmdesktop  %U`
https://aur.archlinux.org/cgit/aur.git/tree/ytmdesktop.desktop?h=ytmdesktop#n5
https://aur.archlinux.org/cgit/aur.git/tree/ytmdesktop.desktop?h=ytmdesktop-git#n5

**Comment by yochananmarqos** [comment]
@varlesh Yep, that works. Thanks!

**Comment by yochananmarqos** [comment]
@BlueManCZ Yep, I just realized that after adding it to the desktop file.
