### ISSUE TITLE
[Icon Request] OpenFortiGUI

### ISSUE THREAD

**Issue by fabiomargarido** [bilelmoussaoui/Hardcode-Tray#648]
### Specifications
- Hardcode-Tray version : `4.3.0`
- Distribution : `Ubuntu 18.04`
- Gtk version : `3.22.30`
- Inkscape version : `0.92.3`
- Cairo version : `1.15.10`
- Sni-qt version: `0.2.7`
- Application name :  `OpenFortiGUI`
- Application website: https://hadler.me/linux/openfortigui/
- Application version : `0.9.0`

**Comment by varlesh** [comment]
this icon can not be fixed, because used from QRC:
https://github.com/theinvisible/openfortigui/blob/master/openfortigui/mainwindow.cpp#L104
https://github.com/theinvisible/openfortigui/blob/master/openfortigui/res.qrc
