### ISSUE TITLE
[Icon Request] Barrier

### ISSUE THREAD

**Issue by fabiomargarido** [bilelmoussaoui/Hardcode-Tray#649]
### Specifications
- Hardcode-Tray version : `4.3.0`
- Distribution : `Ubuntu 18.04`
- Gtk version : `3.22.30`
- Inkscape version : `0.92.3`
- Cairo version : `1.15.10`
- Sni-qt version: `0.2.7`
- Application name :  `Barrier` (https://github.com/debauchee/barrier)
- Application version : `2.3.2`

**Comment by varlesh** [comment]
impossible:
https://github.com/debauchee/barrier/blob/master/src/gui/src/MainWindow.cpp#L299
https://github.com/debauchee/barrier/blob/master/src/gui/src/MainWindow.cpp#L68
