### ISSUE TITLE
Nicotine icon change

### ISSUE THREAD

**Issue by yochananmarqos** [bilelmoussaoui/Hardcode-Tray#655]
### Specifications
- Hardcode-Tray version : `4.3.r119.ga33855c-1`
- Distribution : `Manjaro GNOME`
- Gtk version : `3.24.21-1`
- Inkscape version : `1.0-5`
- Cairo version : `1.17.2+25+gaee96d175-1`
- Application name : `Nicotine +`
- Application version : `2.1.0.dev1.r3032.d3127f6d-1`

The development version added support for AyatanaAppIndicator3 and moved the [tray icons](https://github.com/Nicotine-Plus/nicotine-plus/tree/master/img/tray):

```
/usr/share/icons/hicolor/32x32/apps/org.nicotine_plus.Nicotine_away.png
/usr/share/icons/hicolor/32x32/apps/org.nicotine_plus.Nicotine_connect.png
/usr/share/icons/hicolor/32x32/apps/org.nicotine_plus.Nicotine_disconnect.png
/usr/share/icons/hicolor/32x32/apps/org.nicotine_plus.Nicotine_msg.png
```

The stable version still has the icons in the same place:

```
usr/share/nicotine/trayicons/trayicon_away.png
usr/share/nicotine/trayicons/trayicon_connect.png
usr/share/nicotine/trayicons/trayicon_disconnect.png
usr/share/nicotine/trayicons/trayicon_msg.png
```

**Comment by varlesh** [comment]
This icon not hardcoded anymore:
https://github.com/Nicotine-Plus/nicotine-plus/commit/a62506d89f48a4c87ee6467b3367fb8d7e0a0bae#diff-984e42748e29a712479bef8ca37584f5

**Comment by varlesh** [comment]
with latest git-version nicotine+ & papirus:
![image](https://user-images.githubusercontent.com/8083855/89487341-3b789780-d7b6-11ea-85e0-ec3f826cc5f7.png)
