### ISSUE TITLE
Android Messages unread icon

### ISSUE THREAD

**Issue by yochananmarqos** [bilelmoussaoui/Hardcode-Tray#657]
### Specifications
- Hardcode-Tray version : `4.3.r120.g6ebffea-1`
- Distribution : `Manjaro GNOME`
- Gtk version : `3.24.22-1`
- Inkscape version : `1.0-5`
- Application name :  `Android Messages Desktop`
- Application version : `4.2.0`

There's now an [unread tray icon](https://github.com/OrangeDrangon/android-messages-desktop/commit/2811e5bf731b723a12b196326cab05215a751c35)

**Comment by varlesh** [comment]
updated
