### ISSUE TITLE
[Icon request] JetBrains Toolbox App

### ISSUE THREAD

**Issue by orange-buffalo** [bilelmoussaoui/Hardcode-Tray#658]
- Hardcode-Tray version : `4.3`
- Distribution : `KDE neon 20.04`
- Gtk version : `3.24`
- Application name :  `JetBrains Toolbox App`, https://www.jetbrains.com/toolbox-app/
- Application version : `1.18.7455`

**Comment by varlesh** [comment]
appimage not supported!

**Comment by orange-buffalo** [comment]
I see, sorry for the trouble.
