### ISSUE TITLE
Todoist

### ISSUE THREAD

**Issue by rauldipeas** [bilelmoussaoui/Hardcode-Tray#660]
Any chance to get the new Todoist app on Hardcode-Tray scripts?
https://github.com/KryDos/todoist-linux

**Comment by varlesh** [comment]
It's possible fixed ))
By default on KDE Neon used `icon.png`. Other icons used?
![image](https://user-images.githubusercontent.com/8083855/93618840-ddf87d00-f9e8-11ea-9f14-518bc3791295.png)

**Comment by varlesh** [comment]
added:
![image](https://user-images.githubusercontent.com/8083855/93623011-1bf89f80-f9ef-11ea-8cb6-b59128092088.png)
