### ISSUE TITLE
Cadence

### ISSUE THREAD

**Issue by rauldipeas** [bilelmoussaoui/Hardcode-Tray#665]
How could I fix this?
![image](https://user-images.githubusercontent.com/12108031/98457531-199d0100-2167-11eb-9249-2127b5ceae5f.png)

**Comment by varlesh** [comment]
I think it's possible fixed with `-panel` suffix:
https://github.com/falkTX/Cadence/blob/master/src/systray.py#L100

**Comment by rauldipeas** [comment]
@falkTX can You implement this?

**Comment by varlesh** [comment]
@rauldipeas it's already implemented. All libappindicator-apps used for tray icon `-panel `suffix. Try make symlink `cadence-panel` to any monochrome icon for test.

**Comment by rauldipeas** [comment]
> @rauldipeas it's already implemented. All libappindicator-apps used for tray icon `-panel `suffix. Try make symlink `cadence-panel` to any monochrome icon for test.

I made symlinks on all `panel` folders, don't work.

**Comment by varlesh** [comment]
clear icon cache and try `env DESKTOP_SESSION=ubuntu cadence`

**Comment by rauldipeas** [comment]
Same results... :/
![image](https://user-images.githubusercontent.com/12108031/98458513-31c54e00-2170-11eb-851b-5297903e42d1.png)

**Comment by varlesh** [comment]
need run with `AppIndicator` engine... maybe need set another environment options

**Comment by rauldipeas** [comment]
I'm using __classic systray__ on XFCE.

**Comment by varlesh** [comment]
i'm add tray icons for experiments... try another env options:
https://github.com/falkTX/Cadence/blob/master/src/systray.py#L32-L38

**Comment by varlesh** [comment]
Another solution - added fallback icon (with fix icon size)  for Qt engine:
```
# Get Icon from user theme, using our own as backup (Oxygen)
def getIcon(icon, size=22):
    return QIcon.fromTheme("cadence-panel", icon, QIcon(":/%ix%i/%s.png" % (size, size, icon)))
```

**Comment by varlesh** [comment]
https://github.com/falkTX/Cadence/blob/master/src/systray.py#L67-L69

**Comment by rauldipeas** [comment]
> Another solution - added fallback icon (with fix icon size) for Qt engine:
> 
> ```
> # Get Icon from user theme, using our own as backup (Oxygen)
> def getIcon(icon, size=22):
>     return QIcon.fromTheme("cadence-panel", icon, QIcon(":/%ix%i/%s.png" % (size, size, icon)))
> ```

I'm sorry, i don't know how to do this...

**Comment by varlesh** [comment]
> I'm sorry, i don't know how to do this...

i'm already write this:
Find this on **systray.py**:
```
# Get Icon from user theme, using our own as backup (Oxygen)
def getIcon(icon, size=16):
    return QIcon.fromTheme(icon, QIcon(":/%ix%i/%s.png" % (size, size, icon)))
```
and replace:
```
# Get Icon from user theme, using our own as backup (Oxygen)
def getIcon(icon, size=22):
    return QIcon.fromTheme("cadence-panel", icon, QIcon(":/%ix%i/%s.png" % (size, size, icon)))
```

**Comment by rauldipeas** [comment]
I had to do like this to work...
```
# Get Icon from user theme, using our own as backup (Oxygen)
def getIcon(icon, size=24):
    return QIcon.fromTheme("cadence-panel", QIcon(":/%ix%i/%s.png" % (size, size, icon)))
```

**Comment by varlesh** [comment]
ok... it's not hardcode-tray issue. We not change app icons for launchers
