### ISSUE TITLE
Add support for Sirikali

### ISSUE THREAD

**Issue by guille2306** [bilelmoussaoui/Hardcode-Tray#666]
I would like to get support for Sirikali on hardcode-tray:
https://mhogomchungu.github.io/sirikali/
https://github.com/mhogomchungu/sirikali

### Specifications
- Hardcode-Tray version : 4.3
- Distribution : Kubuntu 20.04
- Gtk version : 3.24
- Application name :  Sirikali
- Application version : 1.4.2

**Comment by varlesh** [comment]
https://github.com/mhogomchungu/sirikali/blob/master/src/utility.cpp#L713

**Comment by varlesh** [comment]
@guille2306 update to 1.4.5 and higher...

**Comment by guille2306** [comment]
Perfect, thanks!

**Comment by varlesh** [comment]
https://download.opensuse.org/repositories/home:/obs_mhogomchungu/xUbuntu_20.04/amd64/sirikali_1.4.7.1604940464.04c0d2b-0_amd64.deb

**Comment by varlesh** [comment]
https://software.opensuse.org//download.html?project=home%3Aobs_mhogomchungu&package=sirikali

**Comment by guille2306** [comment]
Great, thanks again! When I installed it I had to rely on the (outdated) Ubuntu package, it was not in the OBS. You solved two problems in one hit :smiley:
