### ISSUE TITLE
[Icon request] CoreCtrl

### ISSUE THREAD

**Issue by viggy96** [bilelmoussaoui/Hardcode-Tray#667]
### Specifications
- Hardcode-Tray version : `4.3`
- Distribution : `Manjaro GNOME`
- Gtk version : `3.24`
- Inkscape version : `1.0.1` 
- Cairo version : `1.17` 
- Sni-qt version: `0.2.7`
- Application name :  `CoreCtrl`
- Application version : `1.1.1`

A monochrome panel icon was recently added to Papirus: https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/blob/master/Papirus/24x24/panel/corectrl-panel.svg

It would be nice if Hardcode-Tray could automate the replacement of the existing colour panel icon with the monochrome one.

**Comment by varlesh** [comment]
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/2247#issuecomment-729392905
