### ISSUE TITLE
QTalarm alarm clock very stubborn tray icon

### ISSUE THREAD

**Issue by katgetscash** [bilelmoussaoui/Hardcode-Tray#668]
[###]([url](url)) [Image of problematic behavior](https://imgur.com/DHCGM8d)

**Specifications**:
- Hardcode-Tray version : v4.3 git
- Distribution : openSUSE tumbleweed KDE
- Gtk version : 3.0
- RSVG-convert 
- Sni-qt version: Patched sni-qt Community 0.2.8.git.1496001340.... 
- Application name :  QTalarm
- Application version : 2.1.0 

### Expected behavior and actual behavior
Hello and good day. Am attempting to change hard-coded tray icon for QTalarm using this script in different ways. So far, have followed the instructions for building successfully, but this one application refuses to cooperate with my other tray icons.

### Steps to reproduce the problem
1. Building both apps from source, same outcome. Apps install and work correctly for other apps, but this app seems to have an qt qrc icon  that will not obey even when replaced manually according to package maintainer in (/usr/share/icons/hicolor, 16x16, 24x24, and 32 x32 respectively.) This also doesn't seem to be affected by running the Hardcode-Tray app for my icon theme (papirus-dark 22px, and hicolor, or clearing the cache and starting over.
2. Have tried following along with other recommendations here but this app uses PNG, conversion from SVG works everywhere else but in the tray. Is there a specific JSON entry or something else I am missing? 
3. Any ideas at this point? Thank you for taking a look at this request. 

Regards,

**Comment by varlesh** [comment]
Yes, it's impossible. Used icons from [binary QRC](https://github.com/CountMurphy/QTalarm/blob/master/mainwindow.cpp#L67):
```
trayIcon->setIcon(QIcon(":/new/icons/Clock.png"));
```
open issue on QTalarm dev for add option use tray icon from theme+fallback icon:
`trayIcon->setIcon((QIcon::fromTheme("qtalarm-tray", QIcon(":/new/icons/Clock.png")));`
