### ISSUE TITLE
Discord icon problem

### ISSUE THREAD

**Issue by drunkdos** [bilelmoussaoui/Hardcode-Tray#670]
### Specifications
- Hardcode-Tray version : `last`
- Distribution : `Lubuntu 20.04`
- Gtk version : `3.24.20-0ubuntu1`
- Application name :  `Discord`
- Application version : `0.0.13`

### Expected behavior and actual behavior
When discord starts up the icon seems fine but when it start completely the icon change again
![screen](https://user-images.githubusercontent.com/58607553/101226548-18db8a00-3695-11eb-93a9-45fa0c6478dd.jpg)
![screen2](https://user-images.githubusercontent.com/58607553/101226058-84bcf300-3693-11eb-9ec0-d57dabf00cad.jpg)

### Steps to reproduce the problem
1. Install discord
2. Run scripts (sudo hardcode-tray --conversion-tool RSVGConvert --theme Papirus then 1)

I'm missing something?

**Comment by varlesh** [comment]
We not support Discord a long time... Tray icons used from binary, it's impossible fixed by hardcode-tray.
PS: I'm remove this configs from database
