### ISSUE TITLE
Versions RegExp VARIABLE for Discord

### ISSUE THREAD

**Issue by varlesh** [bilelmoussaoui/Hardcode-Tray#671]
Discord have 3 versions:
- Stable
- Canary
- PTB
- Development
[Canary](https://aur.archlinux.org/cgit/aur.git/log/?h=discord-canary), [PTB](https://aur.archlinux.org/cgit/aur.git/log/?h=discord-ptb) & [Development](https://aur.archlinux.org/cgit/aur.git/log/?h=discord-development) update very often. An this stupid update versions every week, because tray icons located on folder with version number.
**Maybe anybody found solution for this...**
examples path:

- {userhome}/.config/discordcanary/0.0.116/modules/discord_desktop_core/
- {userhome}/.config/discordcanary/0.0.117/modules/discord_desktop_core/
- {userhome}/.config/discordcanary/0.0.118/modules/discord_desktop_core/

and etc...

- {userhome}/.config/discordptb/0.0.23/modules/discord_desktop_core/
- {userhome}/.config/discordptb/0.0.24/modules/discord_desktop_core/
- {userhome}/.config/discordptb/0.0.25/modules/discord_desktop_core/

and etc...

**Comment by varlesh** [comment]
@BlueManCZ @SmartFinn  @rauldipeas

**Comment by varlesh** [comment]
I don't know Python and can offer some not good variants:
1. Drop Canary & PTB versions. Only Stable - that not updated very often.
2. Write in config futured not published release - guess method... It's @SmartFinn idea, but don't like me, but as easy solution for this
If anybody have idea, please WELCOME

**Comment by rauldipeas** [comment]
Drop Canary & PTB, it's not the goal, i think.

**Comment by varlesh** [comment]
@rauldipeas But the updated every week. You want update config every week?

**Comment by varlesh** [comment]
Oh! I found 4 version:
https://aur.archlinux.org/cgit/aur.git/log/?h=discord-development
Guys, it's madness !!!

**Comment by rauldipeas** [comment]
I think that if this need a regular updates on scripts, it's a worthless job, there's no point to maintain.

**Comment by varlesh** [comment]
Yes it's need a regular update on scripts an regular start hardcode-tray (but it's can be solved with cron)

**Comment by varlesh** [comment]
I'm update config for example and info

**Comment by rauldipeas** [comment]
Maybe you should add support to run `hardcode-tray --apply --only $APP` when app package was updated.

**Comment by varlesh** [comment]
This already implemented:
`sudo -E hardcode-tray -ct RSVGConvert --apply --only discord.electron`

**Comment by rauldipeas** [comment]
I meant `discord` package.

**Comment by varlesh** [comment]
@rauldipeas You mean GitHub action + parser. Where you found tags releases?

**Comment by rauldipeas** [comment]
@varlesh I mean an `apt` rule on `hardcode-tray` package, that run script when certain packages(on hardcode-tray database) are updated.

**Comment by SmartFinn** [comment]
@rauldipeas what about other distros? Even not every package manager has post-run scripts.

**Comment by rauldipeas** [comment]
@SmartFinn i can't figure out a implementation for another distros, but on `apt` it's possible.

**Comment by varlesh** [comment]
@rauldipeas It's not solution. Hardcode-tray used on other distros too...

**Comment by rauldipeas** [comment]
I don't think it is...

It's just an idea.

**Comment by varlesh** [comment]
Ok guys... We think (@SmartFinn  & @varlesh ) and decided
1. Discord have 4 versions - it's hard to track
2. Anyway if all config actual you need constant updating and every run hardcode-tray... again & again
It's vicious circle and senselessly
I'm drop non-Stable versions. Want themable tray icons - use stable version
