### ISSUE TITLE
DeltaChat

### ISSUE THREAD

**Issue by rauldipeas** [bilelmoussaoui/Hardcode-Tray#680]
Could you fix DeltaChat?

https://delta.chat

**Comment by varlesh** [comment]
![image](https://user-images.githubusercontent.com/8083855/109258646-1744dc80-7814-11eb-92b3-2562e3aa2e62.png)

waht icons used on tray in Linux?

**Comment by rauldipeas** [comment]
`deltachat.ico` or `deltachat.png`, i'm not shure.

**Comment by varlesh** [comment]
Thx. it's png, usually ico used on Windows only

**Comment by varlesh** [comment]
You use aur?
I can't understand path to asar
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=deltachat-desktop-git#n46

**Comment by varlesh** [comment]
on DEB it located to: 
/opt/DeltaChat/resources/app.asar

**Comment by rauldipeas** [comment]
I'm using DEB.

**Comment by varlesh** [comment]
See on this line, that not packaed asar build:
`cp -r node_modules  images tsc-dist build html-dist _locales "${pkgdir}/opt/DeltaChat/electron_app"`

**Comment by rauldipeas** [comment]
This is folder structure here.
https://del.dog/ecucerfahi.txt

**Comment by varlesh** [comment]
i'm added 2 files:
- deltachat.electron.json for DEB
- deltachat.json for AUR

**Comment by rauldipeas** [comment]
There's an update on files structure.

https://github.com/deltachat/deltachat-desktop/tree/master/images/tray

Now there are two files for tray.

**Comment by rauldipeas** [comment]
Temporary fix...

```
{
    "name": "DeltaChat",
    "app_path": [
        "/opt/DeltaChat/"
    ],
    "icons_path": [
        "/opt/DeltaChat/resources/"
    ],
    "binary": "app.asar",
    "script": "electron",
    "icons": {
        "tray": {
            "original": "images/tray/deltachat.png",
            "theme": "deltachat-tray"
        },
        "tray-unread": {
            "original": "images/tray/deltachat-unread.png",
            "theme": "hipchat4-attention"
        }
    }
}
```
