### ISSUE TITLE
Discord 0.0.14 no longer works

### ISSUE THREAD

**Issue by georgeat8** [bilelmoussaoui/Hardcode-Tray#682]
### Specifications
- Hardcode-Tray version : `hardcode-tray-git 4.3.r15.g46df7ea-1`
- Distribution : `Manjaro KDE`
- Gtk version : `GTK3`
- Application name :  `Discord`
- Application version : `0.0.14`

### Expected behavior and actual behavior

After a new update to `Discord` (`0.0.13` -> `0.0.14`), the script no longer replaces the tray icon and it seems like it no longer recognizes it when running (see image). 

The command used is:
`sudo -E hardcode-tray --conversion-tool RSVGConvert --size 22 --theme Papirus`

![image](https://user-images.githubusercontent.com/62032417/112293555-f187e780-8c9a-11eb-999a-affd4288af19.png)

### Steps to reproduce the problem
1. Update to the latest `Discord` version
2. Run the script

**Comment by varlesh** [comment]
https://github.com/bilelmoussaoui/Hardcode-Tray/pull/681
