### ISSUE TITLE
Element Desktop and Discord not being detected

### ISSUE THREAD

**Issue by PopeRigby** [bilelmoussaoui/Hardcode-Tray#683]
### Specifications
- Hardcode-Tray version : 4.3
- Distribution :  Arch Linux
- Gtk version : Gtk3 1:3.24.27
- Inkscape version : 1.0.2
- Cairo version :  1.17.4
- Application name :  Element Desktop (1.7.23) & Discord  (Stable 80314)

### Expected behavior and actual behavior
Hardcoded-Tray should detect Element Desktop and Discord and patch the icons, but it doesn't. I think this might be because my Element Desktop and Discord executables are in `/usr/bin` instead of `/opt`, but I'm not sure. I tried using the `--path` argument and pointing it to `/usr/bin/element-desktop` and `/usr/bin/discord`, but that didn't work.

### Steps to reproduce the problem
1. Run `sudo -E hardcode-tray --conversion-tool RSVGConvert --size 22`

**Comment by varlesh** [comment]
discord fixed, see https://github.com/bilelmoussaoui/Hardcode-Tray/pull/681

**Comment by varlesh** [comment]
please show me 
`du -a /usr/lib/element`

**Comment by varlesh** [comment]
with [this comand](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=element-desktop-git#n92) tray icon located on `/usr/lib/element/img/element.png`

**Comment by PopeRigby** [comment]
Thanks for the help, using the master branch build fixed everything.

**Comment by PopeRigby** [comment]
Actually, it says only 1/3 for Discord, and 2/3 for Element when applying. 

> please show me
> `du -a /usr/lib/element`

```
42488	/usr/lib/element/app.asar
0	/usr/lib/element/webapp
4	/usr/lib/element/img/element.png
24	/usr/lib/element/img/element.ico
32	/usr/lib/element/img
42524	/usr/lib/element
```

**Comment by varlesh** [comment]
Why reopen? What not fixed?

**Comment by PopeRigby** [comment]
Oh wait. Does this just mean Discord is the first task, Element is the second, and Steam is the third?
```
Discord             [############........................] 1/3 33.3% 0.21s
Element Desktop     [########################............] 2/3 66.7% 0.01s
Steam               [####################################] 3/3 100.0% 0.01s
```

**Comment by varlesh** [comment]
Yes, it's fixed 3 apps
