### ISSUE TITLE
Discord Canary

### ISSUE THREAD

**Issue by georgeat8** [bilelmoussaoui/Hardcode-Tray#685]
### Specifications
- Hardcode-Tray version : `hardcode-tray-git 4.3.r149.g3e646aa-1`
- Distribution : `Manjaro KDE`
- Gtk version : `GTK3`
- Application name :  `Discord Canary`
- Application version : `0.0.119`

### Expected behavior and actual behavior

Seems that Discord Canary is not supported, as the tray icon doesn't change on running the script, although the script shows that Discord was edited. I currently have only the Canary version installed.

![image](https://user-images.githubusercontent.com/62032417/113412238-6efcd780-93c0-11eb-8e65-1abc4a2eaae1.png)

### Steps to reproduce the problem
1. Install Discord Canary from AUR
2. Run the script

**Comment by varlesh** [comment]
It's pointless, because have very often updates.
https://aur.archlinux.org/cgit/aur.git/log/?h=discord-canary

**Comment by varlesh** [comment]
supported only stable version

**Comment by varlesh** [comment]
Discord have release number on icon path:
```
"icons_path": [
        "{userhome}/.config/discord/0.0.14/modules/discord_desktop_core/"
    ]
```
And this problem for updates

**Comment by georgeat8** [comment]
Yes, that I know. Doesn't seem like such a big update to be done in case of a new version, but I see your point. Will resort to a small script to replace it.

**Comment by varlesh** [comment]
Canary now supported
