### ISSUE TITLE
Psensor icon is blurry. 

### ISSUE THREAD

**Issue by nihakuto** [bilelmoussaoui/Hardcode-Tray#689]
### Specifications
- Hardcode-Tray version : `hardcode-tray 4.3-3 [+25 ~1.36]`
- Distribution : `archlinux 5.11.16-arch1-1`
- Gtk version : `gtk3 1:3.24.29-1`
- Inkscape version : ------
- Cairo version : `cairo 1.17.4-5`
- Sni-qt version: `sni-qt 0.2.7+17.04.20170112-1`
- Application name :  `psensor`
- Application version : `1.2.1-1`

### Expected behavior and actual behavior
Expected: same size/resolution/scaling icon for psensor as for every other tray icon.

Actual:
![image](https://user-images.githubusercontent.com/34426136/116186004-c442b500-a6f0-11eb-82d7-8922cb35d776.png)

### Steps to reproduce the problem
1. Install psensor. Run and kill process once.
2. Apply hardcode-tray as root.
3. Run psensor again.

To illustrate the problem a little better, I tried to replace the .svg icon (that I thought was responsible) with one that works as expected, and I got the exact same problem as before. On the pic below, you can see two steam tray icons - the rightmost one is for actual steam, and the one of the left is the same exact file/code from the steam tray icon put in place of the original psensor_normal.svg

![image](https://user-images.githubusercontent.com/34426136/116186057-e50b0a80-a6f0-11eb-9289-6577d230d184.png)

PS: I have the libappindicator-gtk2 and libappindicator-gtk3 packages installed, as part of trying to solve this issue.

**Comment by varlesh** [comment]
psensor use system icons, it's not hardcode-tray problem.
Anyway, i can't reproduce this:
![image](https://user-images.githubusercontent.com/8083855/116213893-39e16c00-a757-11eb-8290-2092cd01bf98.png)
Try run psensor with Unity env option:
`XDG_CURRENT_DESKTOP=Unity psensor`
or install another libappindicator
also check all system tray items (up arrow button), maybe psensor duplicate tray icons:
https://archived.forum.manjaro.org/t/psensor-duplicated-tray-icon/147321

**Comment by evren320** [comment]
i have exactly same problem, using kde plasma on archlinux with 4k monitor.
 env XDG_CURRENT_DESKTOP=Unity psensor doesn't fix the issue.
i tried to replace /usr/share/icons/hicolor/scalable/apps/psensor_normal.svg with another svg image, new image is also downscaled to 22x22, i also tried to use a png image and rename it as psensor_normal.svg, the png image also shown as downscaled to 22x22.
