### ISSUE TITLE
Tray icon of youtube-music blurry

### ISSUE THREAD

**Issue by JoeJoeTV** [bilelmoussaoui/Hardcode-Tray#695]
### Specifications
- Hardcode-Tray version : `4.3`
- Distribution : `Linux Mint CInnamon 20.1`
- Gtk version : `3.24`
- Inkscape version : `0.92.5`
- Cairo version : `2.5.2`
- Application name :  [`youtube-music`](https://github.com/th-ch/youtube-music)
- Application version : `1.12.2`

### Expected behavior and actual behavior
I just got the update to the papirus icon theme, that supports the tray icon for [youtube-music](https://github.com/th-ch/youtube-music) and after applying and restarting the app, it is changed but looks blurry in comparison to the other icons:
![image](https://user-images.githubusercontent.com/34209417/124599785-56d8a080-de66-11eb-9fc6-6a925e6d0954.png)

Is there a reason, why it is not using an svg icon or simillar? The [Google Play Music Desktop App](https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-) has an icon that is clear using `hadcode-tray`

**Comment by varlesh** [comment]
It's not hardcode-tray or Papirus bug. Icon have fixed size:
https://github.com/th-ch/youtube-music/blob/master/tray.js#L19-L21
