### ISSUE TITLE
Why hasn't a release been made in about three years?

### ISSUE THREAD

**Issue by hwittenborn** [bilelmoussaoui/Hardcode-Tray#696]
I'm looking into packaging this (and I'd like to pull from the releases), but it looks like a release hasn't been made in about three years. I'm also seeing ~150 commits have been made since the last release.

Is this intentional?

**Comment by varlesh** [comment]
Formaly this repo abandoned. I'm not main developer and only added new apps for support or doing little fixes... AUR & PPA use git-version

**Comment by hwittenborn** [comment]
Sounds good, I'll try to work out a Git package then.
