### ISSUE TITLE
Heroic Games Launcher

### ISSUE THREAD

**Issue by rauldipeas** [bilelmoussaoui/Hardcode-Tray#698]
Can you fix it?

![image](https://user-images.githubusercontent.com/12108031/127800928-f3d25eff-d4d7-479a-9847-15be1b799460.png)

https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher

**Comment by varlesh** [comment]
![image](https://user-images.githubusercontent.com/8083855/127801182-5f4409d2-cbf4-4515-a984-05f30758fd43.png)
By default used light icon? And have option change icon on settings?

**Comment by rauldipeas** [comment]
> ![image](https://user-images.githubusercontent.com/8083855/127801182-5f4409d2-cbf4-4515-a984-05f30758fd43.png)
> By default used light icon? And have option change icon on settings?

Yes, light icon by default with an option to change it to dark.

**Comment by varlesh** [comment]
done
