### ISSUE TITLE
Has icon for Rambox but not for Rambox Pro

### ISSUE THREAD

**Issue by DenysMb** [bilelmoussaoui/Hardcode-Tray#699]
### Specifications
- Hardcode-Tray version : `4.3.3`
- Distribution : `Arch Linux`
- Gtk version : `3.24`
- Application name :  `Rambox Pro`
- Application version : `1.5.2-1`

### Expected behavior and actual behavior
The Rambox Pro app should get the same icon as the Rambox app, but it is different.

### Steps to reproduce the problem
1. Install Rambox and Rambox Pro.
2. Run the hardcode-tray script.
3. Run and see the different icons.

**Comment by varlesh** [comment]
added

**Comment by DenysMb** [comment]
It seems like it didn't work. I had the last version from Hardcode-Tray from Github, ran it, it shows "Rambox" when we apply but the Rambox Pro tray icon remains the same.

**Comment by varlesh** [comment]
What icons used?
![Screenshot_20210814_050800](https://user-images.githubusercontent.com/8083855/129430071-cf6e28f8-946e-4198-aadb-3a0fadc16473.png)

**Comment by varlesh** [comment]
It's different with Rambox icons:
![Screenshot_20210814_051657](https://user-images.githubusercontent.com/8083855/129430241-ef5b82cd-dafe-410b-89ea-e36e49dc4124.png)

**Comment by varlesh** [comment]
active - it's normal state
done.fw - ?
done - ?
inactive - i think it's offline
mention - how draw this?
unread - message
warning - how draw this?

**Comment by varlesh** [comment]
updated on Papirus and here

**Comment by DenysMb** [comment]
> What icons used?
> ![Screenshot_20210814_050800](https://user-images.githubusercontent.com/8083855/129430071-cf6e28f8-946e-4198-aadb-3a0fadc16473.png)

The strange part is that I never saw the yellow and green icon.  The only three icons that appears for me, using with WhatsApp Web, Discord, Instagram, Telegram, Zoho Mail, Gmail, Microsoft Teams, Slack and Outlook, is the "active", the "mention"/"done" and the "unread".

**Comment by varlesh** [comment]
i'm added almost all icons (except done.fw - it's not have ico Windows version and i don't know what is this):
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/commit/330898b9e69e18090bd62ff1349f0df9b3996ab0

**Comment by varlesh** [comment]
you can test and close, if all fine

**Comment by DenysMb** [comment]
![image](https://user-images.githubusercontent.com/33737137/129439238-4260a97d-98e3-43b4-9aec-5327f1ce61c7.png)
This error is because of something in some recent commit?

**Comment by varlesh** [comment]
Sorry, i'm not attentive.
Updated

**Comment by varlesh** [comment]
@DenysMb worked?

**Comment by DenysMb** [comment]
I am afraid that is not working. It's really weird. The script now don't show an error and, in theory, updates the Rambox Pro icon but the icon remains the same. I deleted the cache, I deleted Rambox Pro, deleted the /opt/ramboxpro folder, reinstalled the app, ran the script and the icon remains the same old icon ):

**Comment by DenysMb** [comment]
It creates the folder **/home/USER/.config/Hardcode-Tray/Rambox Pro/DATE/** and these are the icons inside:
![image](https://user-images.githubusercontent.com/33737137/129504974-d8ba7542-315b-46af-86ad-c0dfdbdf31d8.png)

**Comment by varlesh** [comment]
Maybe they used icons from Windows directory?
Try change all paths:
`sudo sed -i s/linux/win/g /usr/share/hardcode-tray/database/rambox-pro.electron.json`
And restart again

**Comment by DenysMb** [comment]
Did it now and nothing has changed. Can you tell me what these command did?
I saw nothing different in rambox-pro.electron.json

**Comment by DenysMb** [comment]
Deleted my last comment because I forgot to "re-apply". Now it's work.
Thank you!

**Comment by varlesh** [comment]
ok, i'm added win paths

**Comment by DenysMb** [comment]
Hi, @varlesh.
One thing: the icon for for mention or done.fw (probably this second one) is missing:
![image](https://user-images.githubusercontent.com/33737137/129566030-1d4bcaac-03cc-41bd-b2d0-cac1f874461a.png)
The other stats are working normally.

**Comment by varlesh** [comment]
added as mention icon
