### ISSUE TITLE
Add support for whatsapp-nativefier

### ISSUE THREAD

**Issue by FPSUsername** [bilelmoussaoui/Hardcode-Tray#700]
### Specifications
- Hardcode-Tray version : `hardcode-tray 4.3-3`
- Distribution : `Arch`
- Desktop Environment: `KDE Plasma 5.22.4`
- Gtk version : `GTK-3`
- Application name :  `whatsapp-nativefier` ([AUR](https://aur.archlinux.org/packages/whatsapp-nativefier/))
- Application version : `2.2121.6-1`

### Expected behavior and actual behavior
Similar as issue #685

```
$ sudo -E hardcode-tray --conversion-tool RSVGConvert --size 22 --theme Papirus

** (hardcode-tray:88883): WARNING **: 13:47:02.314: Unable to connect to dbus: The connection is closed
Welcome to Hardcode-Tray!
Hardcode-Tray replaces some icons on the binary files of some applications. 
Please close all the running applications before running Hardcode-Tray script.
Desktop Environment: Kde
Scaling Factor: 1
Icon Size: 22
Icon Theme: Papirus
Conversion Tool: RSVGConvert
To Do: All
1 - Apply
2 - Revert
3 - Clear Backup Cache
Please choose: 1
Applying now..


Megasync            [##################..................] 1/2 50.0% 0.00s
Vivaldi             [####################################] 2/2 100.0% 0.02s
Took 0.02s to finish the tasks

Done, Thank you for using the Hardcode-Tray fixer!
```

### Steps to reproduce the problem
1. Install `whatsapp-nativefier` from AUR
2. Run the script as shown in the Papirus icon [README](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme#hardcoded-tray-icons)

**Comment by varlesh** [comment]
added, try it

**Comment by FPSUsername** [comment]
It works, thanks!

**Comment by FPSUsername** [comment]
![Screenshot_20210814_130031](https://user-images.githubusercontent.com/10143926/129445322-11c6a913-603a-49f8-9ae9-5c12ea9f68fd.png)

Found an issue where the WhatsApp icon in the KDE task switcher is also changed, whereas the icons of other apps (including Telegram, which is supported by this program), are kept original (and I think keeping them original is intended).

**Comment by varlesh** [comment]
And what you want for me?
I'm replace only one file

**Comment by varlesh** [comment]
Try StartupWMClass
