### ISSUE TITLE
Flatpak(user installation) apps aren't being updated

### ISSUE THREAD

**Issue by marcelovbcfilho** [bilelmoussaoui/Hardcode-Tray#702]
### Specifications
- Hardcode-Tray version : `4.3`
- Distribution : `Elementary OS 6 stable`
- Gtk version : `3.24`
- Inkscape version : not installed
- Cairo version : not installed
- Sni-qt version: not installed
- Application name :  `Discord, OBS, Slack`
- Application version : `Flatpak version(user installation)`

### Expected behavior and actual behavior
When using apply, these apps should be updated
Image 1 - Showing that discord is installed, but it icon isn't being updated as show in the log
![Screenshot from 2021-08-17 10-33-18](https://user-images.githubusercontent.com/51462138/129735094-367b9bf7-7583-4b9b-bae2-36f16bb5674d.png)

### Steps to reproduce the problem
1. Install flatpak version and run the code to apply papirus theme 
2. ```sudo -E hardcode-tray --conversion-tool RSVGConvert --size 24 --theme Papirus```

### Log
```
➜  ~ sudo -E hardcode-tray --conversion-tool RSVGConvert --size 24 --theme Papirus
Welcome to Hardcode-Tray!
Hardcode-Tray replaces some icons on the binary files of some applications. 
Please close all the running applications before running Hardcode-Tray script.
Desktop Environment: Pantheon
Scaling Factor: 1
Icon Size: 24
Icon Theme: Papirus
Conversion Tool: RSVGConvert
To Do: All
1 - Apply
2 - Revert
3 - Clear Backup Cache
Please choose: 1
Applying now..


No apps to fix!

Done, Thank you for using the Hardcode-Tray fixer!
```

**Comment by varlesh** [comment]
flatpak not supported

**Comment by varlesh** [comment]
@marcelovbcfilho Initial flatpak support added (Slack & Discord)

**Comment by varlesh** [comment]
all supported apps added
