### ISSUE TITLE
Issue with Insync and Manjaro KDE.

### ISSUE THREAD

**Issue by acutbal** [bilelmoussaoui/Hardcode-Tray#706]
### Specifications
- Hardcode-Tray version : 4.3
- Distribution : Manjaro KDE
- Gtk version : 3.24.30
- Inkscape version : No installed
- Cairo version : 1.17.4
- Sni-qt version: No installed
- Application name :  Insync
- Application version : 3.5.1.50115

### Expected behavior and actual behavior
The script should detect Papirus-Light, however, when I run it, the tray icon doesn't change as used to do.

![Screenshot_20210830_211619](https://user-images.githubusercontent.com/2278584/131392745-7a90e479-b95b-4b81-b3ab-0f62c6fdfa45.png)

I don't know if it's KDE, Papirus or Insync, really no idea... The other apps changes correctly.
Best regards!! :smiley:

**Comment by varlesh** [comment]
fixed
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/commit/94db35f8f622740ce71d2d763a3131f1d7219cc3

**Comment by acutbal** [comment]
@varlesh Thank you so much for fixing it so quickly!!
Best regards!! :smile:
