### ISSUE TITLE
[Icon Request] Yakuake

### ISSUE THREAD

**Issue by FPSUsername** [bilelmoussaoui/Hardcode-Tray#707]
### Specifications
- Hardcode-Tray version : `hardcode-tray 4.3-3`
- Distribution : `Arch`
- Desktop Environment: `KDE Plasma 5.22.5`
- Gtk version : `GTK-3`
- Application name :  `yakuake` ([AUR](https://archlinux.org/packages/extra/x86_64/yakuake/))
- Application version : `21.08.0-1`

**Comment by varlesh** [comment]
This icon not hardcoded and used from plasma theme (if available). Similar as vlc
