### ISSUE TITLE
[Icon request] New Rambox icon

### ISSUE THREAD

**Issue by DenysMb** [bilelmoussaoui/Hardcode-Tray#721]
Some hours ago Rambox released the version 2.0, with this version they changed their tray icon.
Now their tray icon is this:  ![image](https://user-images.githubusercontent.com/33737137/149808728-a8e6d095-4241-4ec0-89d8-134e9bf49ff6.png)
Apparently they changed the icons names.

**Comment by varlesh** [comment]
icons and paths updated... but it's not work on KDE (tray icon not show and original too). I try run with `env XDG_CURRENT_DESKTOP=Unity rambox` but this not solved problem. I think it's bug.

**Comment by varlesh** [comment]
Also new Papirus icons not a perfect pixel align, because i don't know how draw fat lines on 16x16px area... Now it's used 1,5px lines thickness
![image](https://user-images.githubusercontent.com/8083855/149843734-1d49d28c-7843-4127-bd26-20a58ddb171d.png)

**Comment by varlesh** [comment]
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/commit/b74235955e4f5b967fa00e51c7ac1457cba22c3a

**Comment by rauldipeas** [comment]
The script need to be updated...
```
{
    "name": "Rambox",
    "app_path": [
        "/opt/rambox/",
        "/opt/Rambox/",
        "/usr/lib/rambox"
    ],
    "icons_path": [
        "/opt/rambox/resources/",
        "/opt/Rambox/resources/",
        "/usr/lib/rambox/resources/"
    ],
    "binary": "app.asar",
    "script": "electron",
    "icons": {
        "tray": {
            "original": "resources/IconTray.png",
            "theme": "rambox-indicator"
        },
        "tray@2x": {
            "original": "resources/IconTray@2x.png",
            "theme": "rambox-indicator"
        },
        "unread": {
            "original": "resources/IconTrayUnread.png",
            "theme": "rambox-notification"
        },
        "unread@2x": {
            "original": "resources/IconTrayUnread@2x.png",
            "theme": "rambox-notification"
        }
    }
}
```

**Comment by varlesh** [comment]
updated
