### ISSUE TITLE
Google Chat

### ISSUE THREAD

**Issue by rauldipeas** [bilelmoussaoui/Hardcode-Tray#723]
Can You fix it?
https://github.com/squalou/google-chat-linux

**Comment by varlesh** [comment]
What icons used:
![image](https://user-images.githubusercontent.com/8083855/166133820-f8ddc4cc-1220-444a-8d31-5b481e637421.png)

**Comment by rauldipeas** [comment]
![image](https://user-images.githubusercontent.com/12108031/166134067-eaf3478b-4fe0-49d8-a832-362ea80f541e.png)

**Comment by varlesh** [comment]
how about badge, offline, overlay?

**Comment by rauldipeas** [comment]
They follow the same icon type, those circle icons are not used.

**Comment by varlesh** [comment]
done
