### ISSUE TITLE
Megasync tray icon not replaced

### ISSUE THREAD

**Issue by mirenradia** [bilelmoussaoui/Hardcode-Tray#726]
### Specifications
- Hardcode-Tray version : `4.3-0~1115+pkg5~ubuntu20.04.1` (or `4.3` from `hardcode-tray -v` output)
- Distribution : `Ubuntu 20.04.4`
- Gtk: `3.24`
- Inkscape version : `0.92.5-1ubuntu1.1`
- Application name :  `megasync`
- Application version : `4.6.6-5.1`

### Expected behavior and actual behavior
The hardcoded megasync tray icon is not replaced (after a recent update).

### Steps to reproduce the problem
1. Install the above version of `megasync` from [https://mega.io/desktop](https://mega.io/desktop).
2. Run `sudo harcode-tray --apply`

Looking at the output of `dpkg -L megasync`, I can see there are some status icons in `/usr/share/icons/ubuntu-mono-dark/status` which is not in [megasync.json](https://github.com/bilelmoussaoui/Hardcode-Tray/blob/2da90ff5829093f4475bf1d0d044a4d18444867b/data/database/megasync.json) but replacing these manually didn't seem to work for me.

**Comment by varlesh** [comment]
I think this icons now used from binary

**Comment by mirenradia** [comment]
> I think this icons now used from binary

I thought this might be the case but I couldn't see any obvious changes in [their repo](https://github.com/meganz/MEGAsync/commits/master/src/MEGASync/gui).

**Comment by varlesh** [comment]
https://github.com/meganz/MEGAsync/blob/master/src/MEGASync/gui/TransfersStateInfoWidget.cpp#L25-L35

**Comment by mirenradia** [comment]
> https://github.com/meganz/MEGAsync/blob/master/src/MEGASync/gui/TransfersStateInfoWidget.cpp#L25-L35

This file hasn't been modified recently and, from a quick search, nor have the other files that refer to this class (e.g. [TransferStateInfoWidget.ui](https://github.com/meganz/MEGAsync/blob/master/src/MEGASync/gui/linux/TransfersStateInfoWidget.ui)).

**Comment by varlesh** [comment]
But Mega support added in [2017](https://github.com/bilelmoussaoui/Hardcode-Tray/commits/master/data/database/megasync.json)  (on 2021 added flatpak version for all apps ONLY, but not checked)
I can't doing anything. You can check replaced tray icons or not (on **/usr/share/icons/hicolor/scalable/status** directory).
If replcaced, but on application used red icons - this means that they are used from binary.

**Comment by mirenradia** [comment]
> But Mega support added in [2017](https://github.com/bilelmoussaoui/Hardcode-Tray/commits/master/data/database/megasync.json) (on 2021 added flatpak version for all apps ONLY, but not checked) I can't doing anything. You can check replaced tray icons or not (on **/usr/share/icons/hicolor/scalable/status** directory). If replcaced, but on application used red icons - this means that they are used from binary.

I'm a bit confused by what you mean here. This was working until only a few weeks ago.

**Comment by varlesh** [comment]
Previously, icons were supported, I confirm this. But at what point they began to be used from the binary, I do not remember

**Comment by varlesh** [comment]
Anyway, if now used icons from binary - we can't doing anything. You can install previous versions and check this... if needed.
On last release paths for tray icons not changed:
![image](https://user-images.githubusercontent.com/8083855/167619905-fcea8939-41b3-41ef-8df3-cf326d7b4e37.png)
DEB package Version: 4.6.6-5.1

**Comment by varlesh** [comment]
hardcode-tray database:
```
{
    "name": "Megasync",
    "app_path": [
        "/usr/bin/megasync",
        "/var/lib/flatpak/app/nz.mega.MEGAsync/"
    ],
    "icons_path": [
        "/usr/share/icons/hicolor/scalable/status/",
        "/var/lib/flatpak/app/nz.mega.MEGAsync/current/active/files/share/icons/hicolor/scalable/status/"
    ],
    "icons": {
        "paused": {
            "original": "megapaused.svg",
            "theme": "megapaused"
        },
        "synching": {
            "original": "megasynching.svg",
            "theme": "megasynching"
        },
        "logging": {
            "original": "megalogging.svg",
            "theme": "megalogging"
        },
        "warning": {
            "original": "megawarning.svg",
            "theme": "megawarning"
        },
        "ok": {
            "original": "megauptodate.svg",
            "theme": "megauptodate"
        },
        "alert": {
            "original": "megaalert.svg",
            "theme": "megaalert"
        }
    }
}
```

**Comment by varlesh** [comment]
On KDE worked:
![image](https://user-images.githubusercontent.com/8083855/167621640-3ad0d383-7716-4fa1-b42c-1e5c7a8e2667.png)
Maybe on GTK used `ubuntu-mono-dark` icons?
You can show screenshot?

**Comment by varlesh** [comment]
It's very interested hm... on KDE icons not hardcoded and used from theme:
![image](https://user-images.githubusercontent.com/8083855/167622783-861ef1a0-74c5-44dd-aa0b-9ad154235648.png)

**Comment by varlesh** [comment]
@mirenradia Try run from terminal with this option:
`XDG_CURRENT_DESKTOP=KDE megasync`

**Comment by mirenradia** [comment]
> @mirenradia Try run from terminal with this option: `XDG_CURRENT_DESKTOP=KDE megasync`

Hmm, I'm actually already using KDE Plasma (v5.18.8) so the `XDG_CURRENT_DESKTOP` environment variable is already set to `KDE`.

**Comment by varlesh** [comment]
I'm not use Mega and only test it... But current version 4.6.6 worked fine with Papirus icon theme without hardcode-tray on KDE Neon with Plasma 5.24.4
