### ISSUE TITLE
Dropbox not detected

### ISSUE THREAD

**Issue by ceiphr** [bilelmoussaoui/Hardcode-Tray#728]
### Specifications
- Hardcode-Tray version : `4.3`
- Distribution : `Fedora Workstation 36 (GNOME 42.1)`
- Gtk version : `3.24`
- Inkscape version : `1.2 (dc2aedaf03, 2022-05-15)` if installed
- Cairo version : `` if installed
- Sni-qt version: `` if installed
- Application name :  `Dropbox` (**RPM, not Flatpak**)
- Application version : `149.3.4558`

### Expected behavior and actual behavior

Running `sudo -E hardcode-tray --conversion-tool RSVGConvert --size 22 --theme Papirus` _should_ detect all applications with hard-coded tray icons.

Currently, it detects everything except Dropbox. Dropbox is never shown in the log when running the above command.

I can see the images in `/home/<user>/.dropbox-dist/dropbox-lnx.x86_64-149.3.4558/images/hicolor/16x16/status`. Changing them and restarting Dropbox updates the tray icon.

**NOTE**: Somewhat unrelated, but interestingly, Dropbox will revert the icons after a day or so of use after manually changing them.

### Steps to reproduce the problem
1. Run `sudo -E hardcode-tray --conversion-tool RSVGConvert --size 22 --theme Papirus` or simply `sudo -E hardcode-tray`

**Comment by varlesh** [comment]
as i know Dropbox not hardcoded and use tray icons from icon theme

**Comment by varlesh** [comment]
It's very strange for GNOME ... I'm try version dropbox_2020.03.04_amd64
On depends use this packages:
`Depends: procps, python3-gi (>= 3.12), python3 (>= 3.4.0), libatk1.0-0 (>= 2.10), libc6 (>= 2.19), libcairo2 (>= 1.13), libglib2.0-0 (>= 2.40), libgtk-3-0 (>= 3.10.8), libpango1.0-0 (>= 1.36.3), lsb-release, gir1.2-gdkpixbuf-2.0 (>= 2.30.7), gir1.2-glib-2.0 (>= 1.40.0), gir1.2-gtk-3.0 (>= 3.10.8), gir1.2-pango-1.0 (>= 1.36.3)`
I'm not see appindicator on depends and don't know why this not worked.
Maybe it's problem with GTK icon theme cache?

**Comment by ceiphr** [comment]
I'm silly, I blacklisted Dropbox in `~/.config/hardcode-tray.json` before and forgot.

Thank you for looking into this!
