### ISSUE TITLE
Evernote

### ISSUE THREAD

**Issue by rauldipeas** [bilelmoussaoui/Hardcode-Tray#730]
Hi, can You fix this?
https://github.com/search5/Evernote-for-Linux
![image](https://user-images.githubusercontent.com/12108031/178128368-d91ff729-4d0b-4e53-ac2d-c1dd1e565cc5.png)

**Comment by varlesh** [comment]
icon names and paths?

**Comment by varlesh** [comment]
You can extract archive: `asar e app.asar evernote`

**Comment by varlesh** [comment]
Please test it

**Comment by rauldipeas** [comment]
Flawlessly.
![image](https://user-images.githubusercontent.com/12108031/178131316-98f59614-acc7-4f0d-9ab1-12753595d6c1.png)
