### ISSUE TITLE
Steam icon doesn't change (Arch Linux)

### ISSUE THREAD

**Issue by PoisonFrog** [bilelmoussaoui/Hardcode-Tray#732]
### Specifications
- Hardcode-Tray version : `4.3`
- Distribution : `Arch Linux`
- Gtk version : `3`
- Cairo version : `1.17.6-2`
- Application name :  `Steam`

I downloaded Steam from the official multilib repositories for 32 bit apps and installed hardcode-tray-git from the AUR and hardcode-tray doesn't change the Steam icon for the Papirus one (Papirus-Dark).

**Comment by varlesh** [comment]
On database right path `/usr/share/pixmaps/steam_tray_mono.png`. Also, as i know Steam not hardcoded and use tray icon from current icon theme (if available). For example, KDE Neon:
![image](https://user-images.githubusercontent.com/8083855/178653353-fc3493d6-4094-450a-97ed-dcb0bde3c5b9.png)

**Comment by PoisonFrog** [comment]
> /usr/share/pixmaps/steam_tray_mono.png

![papirustraysteam](https://user-images.githubusercontent.com/74987652/178653944-6852427f-d048-4296-9322-2a086145e31a.png)

The smaller Steam icon is Birdtray using the Steam icon and the bigger one is the real Steam.
I have the /usr/share/pixmaps/steam_tray_mono.png icon, but for some reason Steam is using this bigger icon and you can see by the Telegram size comparison that it is not the same one in your tray.  It is bigger than it should be and the color is #DEDEDE instead of #DFDFDF (my tray icon size is 22 btw).

**Comment by varlesh** [comment]
Hm it's strange why icon not replaced. I'm now test and this worked fine:
![image](https://user-images.githubusercontent.com/8083855/178655461-ded210dc-3bc2-44ac-9aa7-711533c6a4ca.png)

**Comment by varlesh** [comment]
color #dfdfdf and size 22px

**Comment by PoisonFrog** [comment]
> Hm it's strange why icon not replaced. I'm now test and this worked fine)

When I run hardcode-tray it shows in its output that it is applying the Steam fix, but nothing happens to the Steam icon. Maybe an issue with the Steam from the multilibs package from Arch repositories? Idk.

**Comment by varlesh** [comment]
Hm, i'm tested Steam with Oxygen icon theme and see your bug. Icon changed on pixmap folder but not used from this folder.
Maybe tray icon located to another directory?
![image](https://user-images.githubusercontent.com/8083855/178656066-df7a3758-6aed-4861-b3a1-966067896a54.png)

**Comment by varlesh** [comment]
I think I found where this icon is used from `~/.local/share/Steam/public/steam_tray_mono.png`

**Comment by PoisonFrog** [comment]
> Hm, i'm tested Steam with Oxygen icon theme and see your bug. Icon changed on pixmap folder but not used from this folder. Maybe tray icon located to another directory? 

Maybe. I don't really understand what goes on behind the scenes with these tray icons.

**Comment by varlesh** [comment]
Haha, it's really this icon `~/.local/share/Steam/public/steam_tray_mono.png` But can not be changed. When i'm replace this icons , Steam check hash files and run automatical update and rewrite this file.

**Comment by PoisonFrog** [comment]
> Haha, it's really this icon `~/.local/share/Steam/public/steam_tray_mono.png` But can not be changed. When i'm replace this icons , Steam check hash files and run automatical update and rewrite this file.

Damn, that sucks. Well... At least it looks similar to the Papirus tray icons.

**Comment by varlesh** [comment]
I don't know why your DE not used steam tray from Papirus, it's strange. Maybe need tray run with another env option, for example `XDG_CURRENT_DESKTOP=KDE steam` or create icon theme symlinks from `/usr/share/icons` to `~/.local/share/icons/`

**Comment by PoisonFrog** [comment]
> I don't know why your DE not used steam tray from Papirus, it's strange. Maybe need tray run with another env option, for example `env XDG_CURRENT_DESKTOP=KDE steam` or create icon theme symlinks from `/usr/share/icons` to `~/.local/share/icons/`

I tried symlinking and running hardcode-tray as `XDG_CURRENT_DESKTOP=KDE sudo -E hardcode-tray --size 22 --theme Papirus-Dark --only steam`, but neither of them worked. Btw, I'm on Xfce and normally the XDG_CURRENT_DESKTOP is set to XFCE.

**Comment by varlesh** [comment]
Maybe need install some libs? For example, `lib32-libappindicator-gtk2` and `lib32-gdk-pixbuf2`

**Comment by PoisonFrog** [comment]
> Maybe need install some libs? For example, `lib32-libappindicator-gtk2` and `lib32-gdk-pixbuf2`

I tried installing these 2 packages and it didn't work.

**Comment by varlesh** [comment]
Sorry, i realy don't know how help you. We are try more things

**Comment by PoisonFrog** [comment]
I had an idea to fix the issue and it worked.

I gave the "~/.local/share/Steam/public/steam_tray_mono.png" file to root and changed permissions to 600 so Steam could not read it. Not a pretty solution, but it works.

Thanks @varlesh for all the help and for locating the file causing the issue.
