### ISSUE TITLE
TickTick

### ISSUE THREAD

**Issue by rauldipeas** [bilelmoussaoui/Hardcode-Tray#733]
**TickTick**

https://ticktick.com

![Screenshot_20220713_181453](https://user-images.githubusercontent.com/12108031/178837435-73d0397e-056a-4689-9260-2128587a3020.png)

The icon name in the launcher had changed too, from `com.ticktick.TickTick` to `ticktick`, maybe You can do the change in the Papirus repository too.

**Comment by varlesh** [comment]
added
