### ISSUE TITLE
Can't install from Ubuntu PPA

### ISSUE THREAD

**Issue by nekolifestyle** [bilelmoussaoui/Hardcode-Tray#744]

**Comment by varlesh** [comment]
try install package from focal

**Comment by pietryszak** [comment]
Confirmed in Ubuntu 22.04
`E: Unable to locate package hardcode-tray`

**Comment by rauldipeas** [comment]
Go ahed with a temporary fix...
```bash
sudo add-apt-repository ppa:papirus/hardcode-tray
sed -i 's/jammy/focal/g' /etc/apt/sources.list.d/*hardcode-tray* #temp-fix
pkcon refresh
pkcon install hardcode-tray
```

**Comment by eight85** [comment]
> Go ahed with a temporary fix...
> 
> ```shell
> sudo add-apt-repository ppa:papirus/hardcode-tray
> sed -i 's/jammy/focal/g' /etc/apt/sources.list.d/*hardcode-tray* #temp-fix
> pkcon refresh
> pkcon install hardcode-tray
> ```

 pkcon install hardcode-tray
Resolving                     [=========================]         Package not found: hardcode-tray
                              [=========================]         Package not found: hardcode-tray
Command failed: This tool could not find any available package.

**Comment by rauldipeas** [comment]
> > Go ahed with a temporary fix...
> > ```shell
> > sudo add-apt-repository ppa:papirus/hardcode-tray
> > sed -i 's/jammy/focal/g' /etc/apt/sources.list.d/*hardcode-tray* #temp-fix
> > pkcon refresh
> > pkcon install hardcode-tray
> > ```
> 
> pkcon install hardcode-tray Resolving [=========================] Package not found: hardcode-tray [=========================] Package not found: hardcode-tray Command failed: This tool could not find any available package.

You should use `sed` with `sudo`...

```bash
sudo add-apt-repository ppa:papirus/hardcode-tray
sudo sed -i 's/jammy/focal/g' /etc/apt/sources.list.d/*hardcode-tray* #temp-fix
pkcon refresh
pkcon install hardcode-tray
```

**Comment by eight85** [comment]
I still get the same error but I'm also running 22.10 now

**Comment by eight85** [comment]
are the builds for kinetic and jammy currently broken?



hardcode-tray - 4.3-0~1133+pkg7~ubuntu22.10.1 | (changes file) | no signer | 2023-01-17 | Published | Kinetic | Misc | amd64
-- | -- | -- | -- | -- | -- | -- | --
hardcode-tray - 4.3-0~1133+pkg7~ubuntu22.04.1 | (changes file) | no signer | 2023-01-17 | Published | Jammy | Misc | amd64

```
hardcode-tray - 4.3-0~1133+pkg7~ubuntu22.10.1 	[(changes file)](https://launchpad.net/~papirus/+archive/ubuntu/hardcode-tray/+files/hardcode-tray_4.3-0~1133+pkg7~ubuntu22.10.1_source.changes) 	no signer 	2023-01-17 	Published 	Kinetic 	Misc 	There were build failures. amd64
hardcode-tray - 4.3-0~1133+pkg7~ubuntu22.04.1 	[(changes file)](https://launchpad.net/~papirus/+archive/ubuntu/hardcode-tray/+files/hardcode-tray_4.3-0~1133+pkg7~ubuntu22.04.1_source.changes) 	no signer 	2023-01-17 	Published 	Jammy 	Misc 	There were build failures. amd64
```

**Comment by rauldipeas** [comment]
So change "jammy" to "kinnect".
```bash
sudo add-apt-repository ppa:papirus/hardcode-tray
sudo sed -i 's/kinetic/focal/g' /etc/apt/sources.list.d/*hardcode-tray* #temp-fix
pkcon refresh
pkcon install hardcode-tray
```

**Comment by eight85** [comment]
> ```shell
> sudo sed -i 's/kinetic/focal/g' /etc/apt/sources.list.d/*hardcode-tray* #temp-fix
> ```

pkcon install hardcode-tray
Resolving                     [=========================]         
Testing changes               [=========================]         
Finished                      [                         ] (0%)  
The following packages have to be installed:
 gir1.2-rsvg-2.0-2.54.4+dfsg-1ubuntu1.amd64     gir files for renderer library for SVG files
 hardcode-tray-4.3-0~1133+pkg6~ubuntu20.04.1.all        Fixes Hardcoded tray icons in Linux
 librsvg2-bin-2.54.4+dfsg-1ubuntu1.amd64        command-line utility to convert SVG files
Proceed with changes? [N/y]

Its trying to install the 20.04 build with this..

**Comment by rauldipeas** [comment]
This is a temporary fix.

**Comment by pietryszak** [comment]
23.04 not working.  It's time to make decision like update ppa or abandon project.
